### PR TITLE
Get configuration values of traj_exec_man

### PR DESCRIPTION
**Pull request by MatthijsBurgh**
### Description

Get configuration values of the trajectory_execution_mananager

### Checklist
- [x] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [x] Extend the tutorials / documentation [reference](http://moveit.ros.org/documentation/contributing/)
- [x] Document API changes relevant to the user in the [MIGRATION.md](https://github.com/ros-planning/moveit2/blob/main/MIGRATION.md) notes
- [x] Create tests, which fail without this PR [reference](https://moveit.picknik.ai/humble/doc/examples/tests/tests_tutorial.html)
- [x] Include a screenshot if changing a GUI
- [x] While waiting for someone to review your request, please help review [another open pull request](https://github.com/ros-planning/moveit2/pulls) to support the maintainers

### CODE REVIEW

**Review by tylerjw — APPROVED** [review]

**Comment by tylerjw** [comment]
I'm happy with this PR but to keep clang-tidy happy, would you mind renaming the new methods you added to keep with the style asked for by our config?

Here is an excerpt from the failing CI job.

```
/home/runner/work/moveit2/moveit2/.work/target_ws/src/moveit2/moveit_ros/planning/trajectory_execution_manager/include/moveit/trajectory_execution_manager/trajectory_execution_manager.h:197:8: warning: invalid case style for method 'ExecutionDurationMonitoring' [readability-identifier-naming]
    bool ExecutionDurationMonitoring() const;
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
         executionDurationMonitoring
  /home/runner/work/moveit2/moveit2/.work/target_ws/src/moveit2/moveit_ros/planning/trajectory_execution_manager/src/trajectory_execution_manager.cpp:258:34: note: FIX-IT applied suggested code changes
  bool TrajectoryExecutionManager::ExecutionDurationMonitoring() const
                                   ^
  /home/runner/work/moveit2/moveit2/.work/target_ws/src/moveit2/moveit_ros/planning/trajectory_execution_manager/include/moveit/trajectory_execution_manager/trajectory_execution_manager.h:197:8: note: FIX-IT applied suggested code changes
    bool ExecutionDurationMonitoring() const;
         ^
```

**Comment by MatthijsBurgh** [comment]
I did run the pre-commit, but that didn't notify me/fix it. Could you maybe extend the pre-commit config, so this would show up before committing?

I will update the PR manually for now.

**Comment by MatthijsBurgh** [comment]
@tylerjw See https://github.com/pocc/pre-commit-hooks for a clang-tidy hook. Also listed on the 'official' pre-commit hooks list

**Comment by tylerjw** [comment]
We've tried running clang-tidy in pre-commit but sadly it takes so long to execute it is really annoying for most people. Also, it depends on you having compiled the code with clang.

I wish I had a better solution than running it in CI.

**Pull request merged**
