### PR TITLE
Fix clang-tidy issues

### PR DESCRIPTION
**Pull request by rhaschke**
Having the clang-tidy check `performance-unnecessary-value-param` disabled for a few years, lead to the [introduction of several shortcomings in the code](https://github.com/ros-planning/moveit2/actions/runs/3427540403), which should be fixed asap.
Applying all automatic fixes from clang-tidy is not a good idea as you can see from [second commit, trying to cleanup a few of them](https://github.com/ros-planning/moveit2/pull/1706/commits/25c798e9e3726ca76b672ec04a828ef358d15a75). Somebody from the MoveIt2 team should take over and clean up the remaining ones. @henningkayser, can you please coordinate this work?

### CODE REVIEW

**Comment by henningkayser** [comment]
I think I got most of them. I'm still seeing some "candidate function not viable: no known conversion ..." errors locally, will look into it tomorrow.

**Comment by henningkayser** [comment]
With the last commit, clang-tidy succeeds for me locally

**Review by rhaschke — COMMENTED** [review]
Thanks for handling this, Hennig. There are a few clang warnings left though (which cannot be resolved automatically).

**Comment by henningkayser** [comment]
> Thanks for handling this, Hennig. There are a few clang warnings left though (which cannot be resolved automatically).

What warnings are you talking about? CI is happy and locally I don't see related warnings or errors anymore either?

**Review by AndyZe — APPROVED** [review]
I don't see any warnings locally, either.

**Comment by rhaschke** [comment]
CI doesn't use `-Werror` when building with `clang`. Thus, CI reports success. But if you open the `build_target_workspace` section, you will see a few warnings. Most of them are related to `gmock`, which will be fixed via https://github.com/ament/googletest/pull/21 and https://github.com/ament/ament_cmake/pull/408. However, there a few others as well. Maybe you should use `-Werror` for the clang build as well (if the gmock issues are resolved upstream).

**Comment by rhaschke** [comment]
I approve as well. The warnings can be tackled later as well. This PR should be merged soon to unblock other PRs (which currently will fail due to clang-tidy issues).

**Pull request merged**
