### PR TITLE
Refactor and open the Python interface of planning_interface module

### PR DESCRIPTION
**Pull request by larrylu0426**
Abstract:
Replace the Python binding method based on boost_python in the existed code with pybind11. 

Main Idea:
To keep the existed function no changed, and use the inheritance method(seen in move_group_interface.cpp) to wrap the existed C++ APIs.

Contributions:
1. Replace boost python with pybind11, and keep the name and style of existed APIs as stable as possible;
2. Adapt the old ROS1-related codes;
3. Open both C++  and Python APIs about robot interface;
4. Open and refactor the Python APIs about rclcpp interface/move_group interface/planning_scene interface.

### CODE REVIEW

**Comment by tylerjw** [comment]
Hello @larrylu0426, thank you for the PR. I see you targetted foxy with this, would you consider making a similar PR against the `main` branch to target rolling and humble?

**Comment by larrylu0426** [comment]
Got it. So I need to setup a new environment to test if it can work. Pls wait me some days.

**Comment by larrylu0426** [comment]
> Hello @larrylu0426, thank you for the PR. I see you targetted foxy with this, would you consider making a similar PR against the `main` branch to target rolling and humble?

Got it. So I need to setup a new environment to test if it can work. Pls wait me some days.

**Comment by peterdavidfagan** [comment]
Hi @larrylu0426, 

I am working on a new package called `moveit_py`, the goal of this python package is to bind many of the moveit library functionalities into a single python package. 

It should contain the similar functionalities to the `moveit_commander` package as well as a lot of other functionalities. 

I wished to ask if you wanted to author/co-author parts of the bindings for the planning_scene_interface based on the work you have completed already?

**Comment by larrylu0426** [comment]
> Hi @larrylu0426,
> 
> I am working on a new package called `moveit_py`, the goal of this python package is to bind many of the moveit library functionalities into a single python package.
> 
> It should contain the similar functionalities to the `moveit_commander` package as well as a lot of other functionalities.
> 
> Part of the goal of this package is to unify all the python bindings of moveit under a single python package. I wished to ask if you wanted to author/co-author parts of the bindings for the planning_scene_interface based on the work you have completed already?
> 
> I spoke with my project supervisor and he strongly agrees that it makes sense to incorporate your code. If it works for you we can setup a call to discuss further.

Hi @peterdavidfagan , I'm happy to see the new package that you're developing. I saw your reply on the issue page #1279[https://github.com/ros-planning/moveit2/issues/1279](url). My opinion is that these two work can go simultaneously. `moveit_py` can be seen as a great promotion to moveit2, and I'm willing to participate in it. When it releases, all Python-related codes could be removed from the repo. But it need anyone to review and discuss its design and architecture. This PR just a light engineering to open the existed but closed Python API. So if this PR can be approved quickly, someone who need the Python APIs recently could use it. :)

**Comment by larrylu0426** [comment]
> Hello @larrylu0426, thank you for the PR. I see you targetted foxy with this, would you consider making a similar PR against the `main` branch to target rolling and humble?

Hi @tylerjw , following your suggestion, I close this PR and will make a new PR which can work on main branch soon.

**Pull request closed without merging**
