### PR TITLE
Seperating a calculation from an action in collision_env

### PR DESCRIPTION
**Pull request by TaMaN2031A**
Separating calculations from actions produces reusable, and more testable code. 
Function setScale contains a calculation. This calculation can be separated into an independent calculation. This calculation iterates over scales of links. It compares them with the to-be-set scale. In case of inequality, it pushes this link into a vector. This vector, called u, will be used in updatePaddingOrScaling. 
Same behavior of setPadding.
### Description

Please explain the changes you made, including a reference to the related issue if applicable

### Checklist
- [ ] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] Extend the tutorials / documentation [reference](http://moveit.ros.org/documentation/contributing/)
- [ ] Document API changes relevant to the user in the [MIGRATION.md](https://github.com/ros-planning/moveit2/blob/main/MIGRATION.md) notes
- [ ] Create tests, which fail without this PR [reference](https://moveit.picknik.ai/humble/doc/examples/tests/tests_tutorial.html)
- [ ] Include a screenshot if changing a GUI
- [ ] While waiting for someone to review your request, please help review [another open pull request](https://github.com/ros-planning/moveit2/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Review by sjahr — CHANGES_REQUESTED** [review]
I don't see how this refactors the action to a calculation. `compareWithScale` still uses the member `robot_model_`

**Comment by TaMaN2031A** [comment]
> I don't see how this refactors the action to a calculation. `compareWithScale` still uses the member `robot_model_`

Does sending robot_model_ as a parameter to this function with the scale-or padding as this function could be used with setPadding also, solve this problem? Or the problem is bigger than this, if yes I'd be very grateful if you explain it to me. 
And thank you for your time.

**Comment by TaMaN2031A** [comment]
> > I don't see how this refactors the action to a calculation. `compareWithScale` still uses the member `robot_model_`
> 
> Does sending links as a parameter to this function with the scale-or padding as this function could be used with setPadding also, solve this problem? Or the problem is bigger than this, if yes I'd be very grateful if you explain it to me. And thank you for your time.

Something like this: 
`std::vector<std::string> CollisionEnv::compareWithScale(const double scale,
                                                        const std::vector<const moveit::core::LinkModel*>& links)
{
  std::vector<std::string> u;
  for (const auto link : links)
  {
    if (getLinkScale(link->getName()) != scale)
      u.push_back(link->getName());
  }
  return u;
}

void CollisionEnv::setScale(const double scale)
{
  if (!validateScale(scale))
    return;
  std::vector<std::string> u;
  const std::vector<const moveit::core::LinkModel*>& links = robot_model_->getLinkModelsWithCollisionGeometry();
  for (const auto link : links)
  {
    link_scale_[link->getName()] = scale;
  }
  u = compareWithScale(scale, links);
  if (!u.empty())
    updatedPaddingOrScaling(u);
}`

**Comment by TaMaN2031A** [comment]
> > I don't see how this refactors the action to a calculation. `compareWithScale` still uses the member `robot_model_`
> 
> Does sending links as a parameter to this function with the scale-or padding as this function could be used with setPadding also, solve this problem? Or the problem is bigger than this, if yes I'd be very grateful if you explain it to me. And thank you for your time.

Something like this: https://drive.google.com/file/d/1fHmlrq7lXFU9qfZoDeqAZzGDZ5v0vU1X/view?usp=sharing

**Comment by TaMaN2031A** [comment]
@sjahr Can you review the pull request?

**Comment by TaMaN2031A** [comment]
@sjahr Could you review the code?

**Comment by sjahr** [comment]
I am sorry, but while this technically extracts a calculation from the function, there is no use in doing so. This simple comparison doesn't need testing nor is it re-used, so the only effect of this change is that the number of lines of code for this functionality blows up. Whether or not these changes make sense highly depends on the context and keeping a balance between applying them and keeping the code in a good structure is important. If you're further interested in contributing to MoveIt I'd recommend fixing one of the many open issues. The ones labeled as "good first issue" are in particular good for beginners. Good luck!

**Comment by TaMaN2031A** [comment]
> I am sorry, but while this technically extracts a calculation from the function, there is no use in doing so. This simple comparison doesn't need testing nor is it re-used, so the only effect of this change is that the number of lines of code for this functionality blows up. Whether or not these changes make sense highly depends on the context and keeping a balance between applying them and keeping the code in a good structure is important. If you're further interested in contributing to MoveIt I'd recommend fixing one of the many open issues. The ones labeled as "good first issue" are in particular good for beginners. Good luck!

 I'll go for these issues as soon as possible inshallah. Thank you very much, Mr. Sebastian!

**Pull request closed without merging**
