### PR TITLE
Fixing _ sufix mistake

### PR DESCRIPTION
**Pull request by JoaoVitorMenezesMagalhaes**
### Description

I have removed the _ sufix from public  struct members. #1689 

### Checklist
- [ ] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] Extend the tutorials / documentation [reference](http://moveit.ros.org/documentation/contributing/)
- [ ] Document API changes relevant to the user in the [MIGRATION.md](https://github.com/ros-planning/moveit/blob/master/MIGRATION.md) notes
- [ ] Create tests, which fail without this PR [reference](https://ros-planning.github.io/moveit_tutorials/doc/tests/tests_tutorial.html)
- [ ] Include a screenshot if changing a GUI
- [ ] While waiting for someone to review your request, please help review [another open pull request](https://github.com/ros-planning/moveit/pulls) to support the maintainers

### CODE REVIEW

**Review by sjahr — COMMENTED** [review]
@JoaoVitorMenezesMagalhaes Thanks a lot for taking over that issue! This looks good so far, but you need to update the names in other files as well when instances of this struct get used. The compiler should show you the locations where this is necessary and you can see it i[n the CI as well](https://github.com/ros-planning/moveit2/actions/runs/3394062973/jobs/5642338100)

**Comment by JoaoVitorMenezesMagalhaes** [comment]
Perfect, I've imagined. I'll try to fix it!!

**Comment by sjahr** [comment]
@JoaoVitorMenezesMagalhaes Looks like you still missed a few changes, are you building your workspace locally to verify it works?

```bash
 [Processing: chomp_motion_planner, moveit_ros_planning]
  --- stderr: chomp_motion_planner
  /home/runner/work/moveit2/moveit2/.work/target_ws/src/moveit2/moveit_planners/chomp/chomp_motion_planner/src/chomp_planner.cpp:59:9: error: no member named 'error_code_' in 'planning_interface::MotionPlanDetailedResponse'; did you mean 'error_code'?
      res.error_code_.val = moveit_msgs::msg::MoveItErrorCodes::FAILURE;
          ^~~~~~~~~~~
          error_code
  /home/runner/work/moveit2/moveit2/.work/target_ws/install/moveit_core/include/moveit/planning_interface/planning_response.h:82:38: note: 'error_code' declared here
    moveit_msgs::msg::MoveItErrorCodes error_code;
                                       ^
  /home/runner/work/moveit2/moveit2/.work/target_ws/src/moveit2/moveit_planners/chomp/chomp_motion_planner/src/chomp_planner.cpp:70:9: error: no member named 'error_code_' in 'planning_interface::MotionPlanDetailedResponse'; did you mean 'error_code'?
      res.error_code_.val = moveit_msgs::msg::MoveItErrorCodes::INVALID_ROBOT_STATE;
          ^~~~~~~~~~~
          error_code
  /home/runner/work/moveit2/moveit2/.work/target_ws/install/moveit_core/include/moveit/planning_interface/planning_response.h:82:38: note: 'error_code' declared here
    moveit_msgs::msg::MoveItErrorCodes error_code;
                                       ^
  /home/runner/work/moveit2/moveit2/.work/target_ws/src/moveit2/moveit_planners/chomp/chomp_motion_planner/src/chomp_planner.cpp:80:9: error: no member named 'error_code_' in 'planning_interface::MotionPlanDetailedResponse'; did you mean 'error_code'?
      res.error_code_.val = moveit_msgs::msg::MoveItErrorCodes::INVALID_GOAL_CONSTRAINTS;
          ^~~~~~~~~~~
          error_code
  /home/runner/work/moveit2/moveit2/.work/target_ws/install/moveit_core/include/moveit/planning_interface/planning_response.h:82:38: note: 'error_code' declared here
    moveit_msgs::msg::MoveItErrorCodes error_code;
                                       ^
  /home/runner/work/moveit2/moveit2/.work/target_ws/src/moveit2/moveit_planners/chomp/chomp_motion_planner/src/chomp_planner.cpp:88:9: error: no member named 'error_code_' in 'planning_interface::MotionPlanDetailedResponse'; did you mean 'error_code'?
      res.error_code_.val = moveit_msgs::msg::MoveItErrorCodes::INVALID_GOAL_CONSTRAINTS;
          ^~~~~~~~~~~
          error_code
  /home/runner/work/moveit2/moveit2/.work/target_ws/install/moveit_core/include/moveit/planning_interface/planning_response.h:82:38: note: 'error_code' declared here
    moveit_msgs::msg::MoveItErrorCodes error_code;
                                       ^
  /home/runner/work/moveit2/moveit2/.work/target_ws/src/moveit2/moveit_planners/chomp/chomp_motion_planner/src/chomp_planner.cpp:99:9: error: no member named 'error_code_' in 'planning_interface::MotionPlanDetailedResponse'; did you mean 'error_code'?
      res.error_code_.val = moveit_msgs::msg::MoveItErrorCodes::INVALID_ROBOT_STATE;
          ^~~~~~~~~~~
          error_code
  /home/runner/work/moveit2/moveit2/.work/target_ws/install/moveit_core/include/moveit/planning_interface/planning_response.h:82:38: note: 'error_code' declared here
    moveit_msgs::msg::MoveItErrorCodes error_code;
                                       ^
  /home/runner/work/moveit2/moveit2/.work/target_ws/src/moveit2/moveit_planners/chomp/chomp_motion_planner/src/chomp_planner.cpp:134:48: error: no member named 'trajectory_' in 'planning_interface::MotionPlanDetailedResponse'; did you mean 'trajectory'?
      if (!(trajectory.fillInFromTrajectory(*res.trajectory_[0])))
                                                 ^~~~~~~~~~~
                                                 trajectory
  /home/runner/work/moveit2/moveit2/.work/target_ws/install/moveit_core/include/moveit/planning_interface/planning_response.h:79:53: note: 'trajectory' declared here
    std::vector<robot_trajectory::RobotTrajectoryPtr> trajectory;
                                                      ^
  /home/runner/work/moveit2/moveit2/.work/target_ws/src/moveit2/moveit_planners/chomp/chomp_motion_planner/src/chomp_planner.cpp:187:11: error: no member named 'error_code_' in 'planning_interface::MotionPlanDetailedResponse'; did you mean 'error_code'?
        res.error_code_.val = moveit_msgs::msg::MoveItErrorCodes::PLANNING_FAILED;
            ^~~~~~~~~~~
            error_code
  /home/runner/work/moveit2/moveit2/.work/target_ws/install/moveit_core/include/moveit/planning_interface/planning_response.h:82:38: note: 'error_code' declared here
    moveit_msgs::msg::MoveItErrorCodes error_code;
                                       ^
  /home/runner/work/moveit2/moveit2/.work/target_ws/src/moveit2/moveit_planners/chomp/chomp_motion_planner/src/chomp_planner.cpp:246:7: error: no member named 'trajectory_' in 'planning_interface::MotionPlanDetailedResponse'; did you mean 'trajectory'?
    res.trajectory_.resize(1);
        ^~~~~~~~~~~
        trajectory
  /home/runner/work/moveit2/moveit2/.work/target_ws/install/moveit_core/include/moveit/planning_interface/planning_response.h:79:53: note: 'trajectory' declared here
    std::vector<robot_trajectory::RobotTrajectoryPtr> trajectory;
                                                      ^
  /home/runner/work/moveit2/moveit2/.work/target_ws/src/moveit2/moveit_planners/chomp/chomp_motion_planner/src/chomp_planner.cpp:247:7: error: no member named 'trajectory_' in 'planning_interface::MotionPlanDetailedResponse'; did you mean 'trajectory'?
    res.trajectory_[0] = result;
        ^~~~~~~~~~~
        trajectory
  /home/runner/work/moveit2/moveit2/.work/target_ws/install/moveit_core/include/moveit/planning_interface/planning_response.h:79:53: note: 'trajectory' declared here
    std::vector<robot_trajectory::RobotTrajectoryPtr> trajectory;
                                                      ^
  /home/runner/work/moveit2/moveit2/.work/target_ws/src/moveit2/moveit_planners/chomp/chomp_motion_planner/src/chomp_planner.cpp:253:7: error: no member named 'error_code_' in 'planning_interface::MotionPlanDetailedResponse'; did you mean 'error_code'?
    res.error_code_.val = moveit_msgs::msg::MoveItErrorCodes::SUCCESS;
        ^~~~~~~~~~~
        error_code
  /home/runner/work/moveit2/moveit2/.work/target_ws/install/moveit_core/include/moveit/planning_interface/planning_response.h:82:38: note: 'error_code' declared here
    moveit_msgs::msg::MoveItErrorCodes error_code;
                                       ^
  /home/runner/work/moveit2/moveit2/.work/target_ws/src/moveit2/moveit_planners/chomp/chomp_motion_planner/src/chomp_planner.cpp:254:7: error: no member named 'processing_time_' in 'planning_interface::MotionPlanDetailedResponse'; did you mean 'processing_time'?
    res.processing_time_.resize(1);
        ^~~~~~~~~~~~~~~~
        processing_time
  /home/runner/work/moveit2/moveit2/.work/target_ws/install/moveit_core/include/moveit/planning_interface/planning_response.h:81:23: note: 'processing_time' declared here
    std::vector<double> processing_time;
                        ^
  /home/runner/work/moveit2/moveit2/.work/target_ws/src/moveit2/moveit_planners/chomp/chomp_motion_planner/src/chomp_planner.cpp:255:7: error: no member named 'processing_time_' in 'planning_interface::MotionPlanDetailedResponse'; did you mean 'processing_time'?
    res.processing_time_[0] = std::chrono::duration<double>(std::chrono::system_clock::now() - start_time).count();
        ^~~~~~~~~~~~~~~~
        processing_time
  /home/runner/work/moveit2/moveit2/.work/target_ws/install/moveit_core/include/moveit/planning_interface/planning_response.h:81:23: note: 'processing_time' declared here
    std::vector<double> processing_time;
                        ^
  /home/runner/work/moveit2/moveit2/.work/target_ws/src/moveit2/moveit_planners/chomp/chomp_motion_planner/src/chomp_planner.cpp:261:9: error: no member named 'error_code_' in 'planning_interface::MotionPlanDetailedResponse'; did you mean 'error_code'?
      res.error_code_.val = moveit_msgs::msg::MoveItErrorCodes::INVALID_MOTION_PLAN;
          ^~~~~~~~~~~
          error_code
  /home/runner/work/moveit2/moveit2/.work/target_ws/install/moveit_core/include/moveit/planning_interface/planning_response.h:82:38: note: 'error_code' declared here
    moveit_msgs::msg::MoveItErrorCodes error_code;
                                       ^
  /home/runner/work/moveit2/moveit2/.work/target_ws/src/moveit2/moveit_planners/chomp/chomp_motion_planner/src/chomp_planner.cpp:273:11: error: no member named 'error_code_' in 'planning_interface::MotionPlanDetailedResponse'; did you mean 'error_code'?
        res.error_code_.val = moveit_msgs::msg::MoveItErrorCodes::GOAL_CONSTRAINTS_VIOLATED;
            ^~~~~~~~~~~
            error_code
  /home/runner/work/moveit2/moveit2/.work/target_ws/install/moveit_core/include/moveit/planning_interface/planning_response.h:82:38: note: 'error_code' declared here
    moveit_msgs::msg::MoveItErrorCodes error_code;
                                       ^
  /home/runner/work/moveit2/moveit2/.work/target_ws/src/moveit2/moveit_planners/chomp/chomp_motion_planner/src/chomp_planner.cpp:278:7: error: no member named 'processing_time_' in 'planning_interface::MotionPlanDetailedResponse'; did you mean 'processing_time'?
    res.processing_time_.resize(1);
        ^~~~~~~~~~~~~~~~
        processing_time
  /home/runner/work/moveit2/moveit2/.work/target_ws/install/moveit_core/include/moveit/planning_interface/planning_response.h:81:23: note: 'processing_time' declared here
    std::vector<double> processing_time;
                        ^
  /home/runner/work/moveit2/moveit2/.work/target_ws/src/moveit2/moveit_planners/chomp/chomp_motion_planner/src/chomp_planner.cpp:279:7: error: no member named 'processing_time_' in 'planning_interface::MotionPlanDetailedResponse'; did you mean 'processing_time'?
    res.processing_time_[0] = std::chrono::duration<double>(std::chrono::system_clock::now() - start_time).count();
        ^~~~~~~~~~~~~~~~
        processing_time
  /home/runner/work/moveit2/moveit2/.work/target_ws/install/moveit_core/include/moveit/planning_interface/planning_response.h:81:23: note: 'processing_time' declared here
    std::vector<double> processing_time;
                        ^
  16 errors generated.
  gmake[2]: *** [CMakeFiles/chomp_motion_planner.dir/build.make:132: CMakeFiles/chomp_motion_planner.dir/src/chomp_planner.cpp.o] Error 1
  gmake[1]: *** [CMakeFiles/Makefile2:137: CMakeFiles/chomp_motion_planner.dir/all] Error 2
  gmake: *** [Makefile:146: all] Error 2
  ---
  Failed   <<< chomp_motion_planner [1min 2s, exited with code 2]
  Aborted  <<< moveit_ros_planning [1min 2s]
  
  Summary: 7 packages finished [9min 52s]
    1 package failed: chomp_motion_planner
    1 package aborted: moveit_ros_planning
    7 packages had stderr output: chomp_motion_planner moveit_common moveit_configs_utils moveit_core moveit_resources_prbt_support moveit_ros_occupancy_map_monitor moveit_ros_planning
    31 packages not processed
'build_target_workspace' returned with code '2' after 9 min 53 sec
```

**Comment by sjahr** [comment]
@JoaoVitorMenezesMagalhaes Based on your comment in the 'add skill 21' issue I assume you don't continue this work. I'll close this PR

**Pull request closed without merging**
