### PR TITLE
melodic-devel sync

### PR DESCRIPTION
**Pull request by rhaschke**
Replacement for #35, which has a weird commit history (using two merge commits). This one is cleaner and already includes some of the most recent merges in MoveIt 1. All conflicts are resolved the same way Henning did in #35 - thanks for preparing this.

In contrast to the merge-strategy suggested in https://github.com/ros-planning/moveit2/pull/26#issue-255589277, I propose the following for the future:

```sh
git clone https://github.com/ros-planning/moveit2
cd moveit2
git fetch https://github.com/ros-planning/moveit master  # fetch MoveIt 1 branch
git merge FETCH_HEAD  # and merge into MoveIt 2 head
```
If approved, such a sync PR should be "merged" manually using **`fast-forward`**. github's web interface doesn't provide such an option!
Using github's merge commit, will create another, superfluous commit and squashing or rebasing doesn't make sense at all.
However, looks like @davetcoleman has forbidden to push to the MoveIt 2 repo from cmdline. This is a typical use case, where interaction from cmdline _is_ desirable :wink:

**When there are no merge conflicts**, the following procedure using github's web interface will work too:
```sh
git clone https://github.com/ros-planning/moveit2
cd moveit2
git fetch https://github.com/ros-planning/moveit master  # fetch MoveIt 1 branch
git checkout -b melodic-sync FETCH_HEAD  # check it out as branch melodic-sync
git push origin melodic-sync  # push to file a PR
```
Subsequently, file a PR for the created `melodic-sync` branch and merge using a standard merge-commit.

### CODE REVIEW

**Comment by vmayoral** [comment]
Thanks @rhaschke and @henningkayser. 

After merging and applying some changes https://github.com/AcutronicRobotics/moveit2/commit/4142567f3f5cbbbbbf0d63d080bd8c6711e2fd69, CI passed. 

@vmayoral approves this PR.

**Comment by henningkayser** [comment]
@rhaschke approved.
I think it would make sense to cherry-pick https://github.com/AcutronicRobotics/moveit2/commit/4142567f3f5cbbbbbf0d63d080bd8c6711e2fd69 since it  ports new code to ROS2. It might need an additional clang-format though, some lines are too long.

**Comment by davetcoleman** [comment]
I've responded here:
https://github.com/ros-planning/moveit2/issues/45

**Comment by vmayoral** [comment]
Before looking into https://github.com/ros-planning/moveit2/pull/47, has anyone cherry-picked https://github.com/AcutronicRobotics/moveit2/commit/4142567f3f5cbbbbbf0d63d080bd8c6711e2fd69? I'd prefer to avoid redoing this work in the future so let's keep as close as we can to http://github.com/acutronicrobotics/moveit2

@rhaschke and @davetcoleman

**Comment by rhaschke** [comment]
@vmayoral, why don't you open a PR for this?

**Comment by davetcoleman** [comment]
+1 to opening PR so it can be properly reviewed

**Comment by vmayoral** [comment]
@rhaschke and @davetcoleman, please review https://github.com/ros-planning/moveit2/pull/52

**Pull request merged**
