### PR TITLE
Load panda_hand_controller in run_move_group

### PR DESCRIPTION
**Pull request by JafarAbdi**
### Description

Depends on https://github.com/ros-planning/moveit_resources/pull/73

### Checklist
- [ ] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] Extend the tutorials / documentation [reference](http://moveit.ros.org/documentation/contributing/)
- [ ] Document API changes relevant to the user in the [MIGRATION.md](https://github.com/ros-planning/moveit/blob/master/MIGRATION.md) notes
- [ ] Create tests, which fail without this PR [reference](https://ros-planning.github.io/moveit_tutorials/doc/tests/tests_tutorial.html)
- [ ] Include a screenshot if changing a GUI
- [ ] While waiting for someone to review your request, please help review [another open pull request](https://github.com/ros-planning/moveit/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Comment by vatanaksoytezer** [comment]
I think we will need to update related tutorial launch files after this gets merged

**Comment by MarqRazz** [comment]
@JafarAbdi this still has the bug of the arm group not updating it's joint values when invoking a plan for the `hand`. Do we have an issue created this bug?
The gripper group always thinks the arm is in this pose
image
`[move_group-4] [moveit_collision_detection_fcl.collision_common]: Found a contact between 'panda_rightfinger' (type 'Robot link') and 'panda_link5' (type 'Robot link'), which constitutes a collision. Contact information is not stored.`

**Comment by JafarAbdi** [comment]
> @JafarAbdi this still has the bug of the arm group not updating it's joint values when invoking a plan for the `hand`. Do we have an issue created this bug?
> The gripper group always thinks the arm is in this pose
> image
> `[move_group-4] [moveit_collision_detection_fcl.collision_common]: Found a contact between 'panda_rightfinger' (type 'Robot link') and 'panda_link5' (type 'Robot link'), which constitutes a collision. Contact information is not stored.`

This [PR](https://github.com/ros-planning/moveit2/pull/455) should fix the bug, I just updated the branch, will merge it once CI passes

**Comment by MarqRazz** [comment]
> This PR should fix the bug, I just updated the branch, will merge it once CI passes

Awesome, thanks Jafar!

**Review by AndyZe — APPROVED** [review]

**Review by MarqRazz — APPROVED** [review]
Pulled the code and tested the hand controller with the MTC demo. Thanks for pointing me to that PR @JafarAbdi!

**Pull request merged**
