### PR TITLE
Make `moveit_servo` listen to Octomap updates

### PR DESCRIPTION
**Pull request by amalnanavati**
### Description

As explained in #2548, the current `moveit_servo` does not respect Octomap collisions. Responding to that, this PR makes the following one-line changes:

1. [Addressing the issue] Start the world geometry monitor when initializing the servo node.

(Instead of enabling the world geometry monitor by default, I'm happy to change it to being controlled by a boolean parameter. Maintainers, let me know if you'd prefer that.)

### Testing

I have tested this code on our local robot setup in ROS2 Humble, where a `move_group` node is the primary planning scene monitor, and a `servo_node` subscribes to its updates over the "monitored_planning_scene" topic. As expected, with these changes the robot treats octomap collisions as any other collision in the planning scene, and without these changes it ignores octomap collisions.

Importantly, I have **not** tested the code in cases where the `servo_node` is the primary planning scene monitor. I imagine it should work as long as developers pass in the save octomap and `sensors_3d.yaml` configuration parameters as they would to a `move_group` with an octomap.

### Checklist
- [x] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [N/A] Extend the tutorials / documentation [reference](http://moveit.ros.org/documentation/contributing/)
- [ ] Document API changes relevant to the user in the [MIGRATION.md](https://github.com/ros-planning/moveit2/blob/main/MIGRATION.md) notes
- [ ] Create tests, which fail without this PR [reference](https://moveit.picknik.ai/humble/doc/examples/tests/tests_tutorial.html)
- [N/A] Include a screenshot if changing a GUI
- [ ] While waiting for someone to review your request, please help review [another open pull request](https://github.com/ros-planning/moveit2/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Review by sjahr — COMMENTED** [review]
Thanks! Please address the comment above

> Please target the main branch for development, we will backport the changes to humble for you if approved and if they don't break API.

This looks fine to me. @AndyZe is there any reason not to activate the WorldGeometryMonitor?

**Review by AndyZe — APPROVED** [review]

**Comment by amalnanavati** [comment]
Done; I rebased onto `main`. Note that I haven't been able to test the version on `main` (since I don't use ROS2 Rolling), but given that it is a one-line change and worked on Humble, and you both have looked it over, I imagine it should be fine.

**Review by sjahr — APPROVED** [review]

**Comment by sjahr** [comment]
Thanks for your contribution!

**Comment by amalnanavati** [comment]
@sjahr any idea what might be causing `humble-ci` to fail? Looking at the [logs](https://github.com/ros-planning/moveit2/actions/runs/7199811625/job/19615742681?pr=2601#step:12:9077), it seems like `ros2_control_node` had a segmentation fault, although none of my changes should impact that.

The only error relevant to my change is that no sensor is configured for the Octomap (log [here](https://github.com/ros-planning/moveit2/actions/runs/7199811625/job/19615742681?pr=2601#step:12:9117)) although I believe that is a non-fatal error.

The only other pointer I have is that in Humble, the correct line is `planning_scene_monitor_->startWorldGeometryMonitor();` whereas in Rolling it is `planning_scene_monitor->startWorldGeometryMonitor();` (no underscore), which may impact the automatic backport.

**Comment by sjahr** [comment]
I don't think that error is related to your change. I'll merge the PR

**Pull request merged**
