### PR TITLE
Fix syntax

### PR DESCRIPTION
**Pull request by sjahr**
### Description

Replace a comma with a semicolon. I am a little bit confused, why did this build before and why doesn't CI complain about this?

### Checklist
- [ ] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] Extend the tutorials / documentation [reference](http://moveit.ros.org/documentation/contributing/)
- [ ] Document API changes relevant to the user in the [MIGRATION.md](https://github.com/ros-planning/moveit/blob/master/MIGRATION.md) notes
- [ ] Create tests, which fail without this PR [reference](https://ros-planning.github.io/moveit_tutorials/doc/tests/tests_tutorial.html)
- [ ] Include a screenshot if changing a GUI
- [ ] While waiting for someone to review your request, please help review [another open pull request](https://github.com/ros-planning/moveit/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Review by AndyZe — APPROVED** [review]
Wow.

**Review by vatanaksoytezer — APPROVED** [review]
Wow indeed, I should investigate why CI didn't catch this.

**Comment by sjahr** [comment]
But this 
```cpp
hp_action_client_ = rclcpp_action::create_client<moveit_msgs::action::HybridPlanner>(node_, "run_hybrid_planning"),
```
builds in my local setup too, so maybe CI is fine.

**Review by tylerjw — APPROVED** [review]
It builds fine because similarly, this is valid c++ syntax:

```
a = 2, b = 3;
```

The comma operator can be used to separate multiple assignment statements, there is no requirement that you have to put a semi-colon at the end of a line, only that you have to finish each statement with them.

SO post about comma operator: https://stackoverflow.com/questions/4352857/what-is-a-comma-separated-set-of-assignments

**Comment by sjahr** [comment]
Ahh, thanks for making this clear, I totally forgot about this syntax option. Should we merge this anyways for uniformity and to avoid further confusion?

**Pull request merged**
