### PR TITLE
sync MoveIt 1 master

### PR DESCRIPTION
**Pull request by rhaschke**

### CODE REVIEW

**Comment by vmayoral** [comment]
Thanks @rhaschke, I can look into this but before doing so, can we please address https://github.com/ros-planning/moveit2/pull/36#issuecomment-473572142. It'll end up being more work for us otherwise.

**Comment by davetcoleman** [comment]
@vmayoral please open PR for your changes requested in #36

**Comment by vmayoral** [comment]
> Merging now as everything in this PR has already been reviewed extensively in the moveit1 repo.

IMHO this is a bad policy and we should reconsider and set up some guidelines for syncing. The fact that they were reviewed for ROS1 doesn't mean we should accept it right away. As seen in previous PRs that were ROS 2-related, these changes won't even compile right away and will cause issues with the CI (see https://github.com/ros-planning/moveit2/pull/52 for the last sync we did).

Note this has caused conflicts at  https://github.com/ros-planning/moveit2/pull/10 or https://github.com/ros-planning/moveit2/pull/41 to name a few. Solving them will take time time.

**Comment by rhaschke** [comment]
I don't exactly understand, _what_ you are complaining about, @vmayoral. Of course, we should carefully review these sync PRs and - as long as we don't yet have a working CI - one should compile them locally for approval. I hope that @davetcoleman has done this before merging. I don't yet have a ROS2 infrastructure, so I cannot help on this. I stated that fact several times.

> As seen in previous PRs that were ROS 2-related, these changes won't even compile right away.

That's a pity indeed. That's why a top-priority should be to get Travis CI working again.

> Note this has caused conflicts at #10 or #41 to name a few. Solving them will take time.

If there is heavy parallel development, it is usually unavoidable that we will face merge conflicts. This cannot be used as an argument to not merge certain PRs.

**Comment by vmayoral** [comment]
> That's a pity indeed. That's why a top-priority should be to get Travis CI working again.

Well @rhaschke, that's my complaint. Syncing shouldn't go forward before looking at these commits first from a ROS 2 perspective. Accepted PRs should go through some sort of alignment with the ongoing development (in ROS 2). Otherwise it will break master and slow us down. We should go through some sort of CI mechanism before accepting PRs, otherwise our own development (and all related PRs) get compromised over and over. I had to rebase and solve conflicts in 8+ PRs the last time we accepted a sync to make it compile.

We indeed need CI. We enabled a simple CI in our own at our fork a couple of weeks ago and submitted a PR to "enable it". https://github.com/ros-planning/moveit2/pull/49 could somehow still do but I understand that something much better is being cooked by @mlautman and the guys at PickNik  (certainly desirable).

> I don't yet have a ROS2 infrastructure, so I cannot help on this. I stated that fact several times.

Let me know if there's something we can do to help here.

**Pull request merged**
