### PR TITLE
Enable `-Wold-style-cast`

### PR DESCRIPTION
**Pull request by ChrisThrasher**
### Description

Add `-Wold-style-cast` and fix all new warnings. Expands on #1628.

In many places I'm just using C++ casts and those are fine. However, the big issue is that all the ROS `_THROTTLE` logging macros (through a few more macros nested within) eventually call `RCUTILS_LOG_CONDITION_THROTTLE_BEFORE` which being from a C library understandably uses a C-style cast. See `rcutils/logging_macros.h:176` copied below for convenience.

```c
/**
 * \def RCUTILS_LOG_CONDITION_THROTTLE_BEFORE
 * A macro initializing and checking the `throttle` condition.
 */
#define RCUTILS_LOG_CONDITION_THROTTLE_BEFORE(get_time_point_value, duration) { \
    static rcutils_duration_value_t __rcutils_logging_duration = RCUTILS_MS_TO_NS((rcutils_duration_value_t)duration); \
    static rcutils_time_point_value_t __rcutils_logging_last_logged = 0; \
    rcutils_time_point_value_t __rcutils_logging_now = 0; \
    bool __rcutils_logging_condition = true; \
    if (get_time_point_value(&__rcutils_logging_now) != RCUTILS_RET_OK) { \
      rcutils_log( \
        &__rcutils_logging_location, RCUTILS_LOG_SEVERITY_ERROR, "", \
        "%s() at %s:%d getting current steady time failed\n", \
        __func__, __FILE__, __LINE__); \
    } else { \
      __rcutils_logging_condition = __rcutils_logging_now >= __rcutils_logging_last_logged + __rcutils_logging_duration; \
    } \
 \
    if (RCUTILS_LIKELY(__rcutils_logging_condition)) { \
      __rcutils_logging_last_logged = __rcutils_logging_now;
```

A proper fix would be to upstream a fix that adds pragmas within these macros that silence the warnings, preferably at the source inside `RCUTILS_LOG_CONDITION_THROTTLE_BEFORE` but potentially at a higher level inside rclcpp macros. My use of `#pragma`s is a noisy but practical option that lets us silence these warnings at the callsite while still enabling the warning which as seen by this PR, has caught many remaining C-style casts.

### Checklist
- [ ] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] Extend the tutorials / documentation [reference](http://moveit.ros.org/documentation/contributing/)
- [ ] Document API changes relevant to the user in the [MIGRATION.md](https://github.com/ros-planning/moveit/blob/master/MIGRATION.md) notes
- [ ] Create tests, which fail without this PR [reference](https://ros-planning.github.io/moveit_tutorials/doc/tests/tests_tutorial.html)
- [ ] Include a screenshot if changing a GUI
- [ ] While waiting for someone to review your request, please help review [another open pull request](https://github.com/ros-planning/moveit/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Comment by henningkayser** [comment]
Thank you for enabling this. I think we should get upstream fixed before merging this, though. Alternatively, wouldn't it be possible to silence these warnings by including rclcpp as [SYSTEM](https://github.com/ament/ament_cmake/blob/rolling/ament_cmake_target_dependencies/cmake/ament_target_dependencies.cmake#L32) dependency?

**Comment by ChrisThrasher** [comment]
> I think we should get upstream fixed before merging this, though. 

Would the rcutils maintainers accept a change that disables a C++ warning in their C library? I wasn't sure about that. These pragma statements are really easy to `grep` for and easy to remove later once this fix is hopefully upstreamed and shipped in a few months. In the meantime I think it's worth having this warning.

> Alternatively, wouldn't it be possible to silence these warnings by including rclcpp as [SYSTEM](https://github.com/ament/ament_cmake/blob/rolling/ament_cmake_target_dependencies/cmake/ament_target_dependencies.cmake#L32) dependency?

Sadly no because the macros expand into something the compiler is treating as 1st party code.

**Review by tylerjw — APPROVED** [review]
I think this is a useful enough warning to live with the pragmas until this is upstreamed. Once it is upstreamed it should be easy enough to grep for and remove them.

**Review by tylerjw — APPROVED** [review]

**Comment by tylerjw** [comment]
@henningkayser I think it is easier to accept this PR now and have Chris make a PR to remove these pragma statements when his upstream change is accepted than to have him rebase or remake this PR in 2-6mo after the upstream change is made.

**Review by vatanaksoytezer — APPROVED** [review]
I think I am happy with the changes as is as well. Thank you for doing this!

**Review by henningkayser — APPROVED** [review]

**Comment by ChrisThrasher** [comment]
Fixed another C-style cast that just got merged. Looks like this PR will have an immediate impact once merged.

**Pull request merged**
