### PR TITLE
Fix python tests

### LINKED ISSUE #1976: MoveIt Python Library: Fix Unit Tests
### Description

The current set of [unit tests](https://github.com/ros-planning/moveit2/tree/main/moveit_py/test/unit) for the Python library have incorrect import statements, this task is to resolve this issue. 

@peterdavidfagan will pick this issue up by EOD.

### PR DESCRIPTION
**Pull request by peterdavidfagan**
### Description

The unittests for the Python library were in a broken state due to incorrect imports. This fixes issues with import statements and any broken test cases. 

Note: a follow up item is to further develop the test cases for the Python library. I plan to address this at some point but will prioritise API documentation over this.

Closes #1976

### CODE REVIEW

**Review by henningkayser — COMMENTED** [review]
Fixes look good. But the tests are currently not enabled as a cmake build target, or otherwise accessible with colcon, correct? At least, CI doesn't seem to notice that tests have been broken.

**Comment by peterdavidfagan** [comment]
> Fixes look good. But the tests are currently not enabled as a cmake build target, or otherwise accessible with colcon, correct?

This is true, I will look to add this as a build target before finishing up for the day.

**Comment by tylerjw** [comment]
Fixes #1976

**Comment by peterdavidfagan** [comment]
Hi @henningkayser, 

I believe this one is ready for review. I have added the unittests to the colcon build as requested. There is one detail that is important which is that the python library is built within a specific test folder for the purposes of running the test cases.

**Comment by peterdavidfagan** [comment]
🚢 ?

**Review by henningkayser — APPROVED** [review]

**Pull request merged**
