### PR TITLE
Remove new operators

### PR DESCRIPTION
**Pull request by senceryazici**
### Description

This PR removes unnecessary new operators and uses make_shared, make_unique instead. Related to #868

### CODE REVIEW

**Review by tylerjw — APPROVED** [review]
Thank you for doing this, it looks like allot of tedious work.

**Comment by senceryazici** [comment]
Yeah, I see pointers everywhere :D @tylerjw

**Review by vatanaksoytezer — APPROVED** [review]
Looks good to me! Thanks Sencer!

**Review by v4hn — APPROVED** [review]
> Yeah, I see pointers everywhere :D

Same here after the review...

**Pull request merged**
