### PR TITLE
Switch to clang-format-14

### LINKED ISSUE #1736: Migrate to clang-format-14
As we are now firmly on Ubuntu 22.04 it makes sense to migrate to clang-format-14.

### PR DESCRIPTION
**Pull request by henningkayser**
Fixes #1736

### CODE REVIEW

**Review by AndyZe — APPROVED** [review]
Note that our installation instructions recommend clang-format-10:

https://moveit.ros.org/install-moveit2/source/

I can make a PR for that, although it will be a little annoying b/c we have different versions for every ROS distro.

**Comment by henningkayser** [comment]
> Note that our installation instructions recommend clang-format-10:
> 
> https://moveit.ros.org/install-moveit2/source/
> 
> I can make a PR for that, although it will be a little annoying b/c we have different versions for every ROS distro.

Right, we should really fix that. Maybe we can even drop the "-10" since we are sticking with the distro default anyway.

**Comment by AndyZe** [comment]
Actually I don't think clang-format is necessary in building MoveIt. Will remove it completely from the installation instructions.

**Comment by henningkayser** [comment]
There is a bunch of stuff that we can probably drop. The typical ROS 2 setup instructions + rosdep should be all we need.

**Pull request merged**
