### PR TITLE
[pilz_industrial_motion_planner] Fix logging

### PR DESCRIPTION
**Pull request by galou**
The name `ss` cannot be used with `RCLCPP_INFO_STREAM`.
This is a bug in rclcpp.

Signed-off-by: Gaël Écorchard <gael.ecorchard@cvut.cz>

### Description

Please explain the changes you made, including a reference to the related issue if applicable

### Checklist
- [x] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] Extend the tutorials / documentation [reference](http://moveit.ros.org/documentation/contributing/)
- [x] Document API changes relevant to the user in the [MIGRATION.md](https://github.com/ros-planning/moveit/blob/master/MIGRATION.md) notes
- [ ] Create tests, which fail without this PR [reference](https://ros-planning.github.io/moveit_tutorials/doc/tests/tests_tutorial.html)
- [ ] Include a screenshot if changing a GUI
- [ ] While waiting for someone to review your request, please help review [another open pull request](https://github.com/ros-planning/moveit/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Comment by v4hn** [comment]
Where is the pull request for rclcpp? Something similar got fixed multiple times ([(1)](https://github.com/ros/rosconsole/commit/4f7572cea43d3f85ca7f8bff7a75174f2d9d758a), [(2)](https://github.com/ros/rosconsole/commit/1357c9d6bf1a836b0e7043a7e67be95f22ee9d60)) in rosconsole before, so I'm very surprised to see the same issues pop up in ROS2 again :angry:

**Comment by galou** [comment]
I'm using Galactic (rclcpp v9.2.0) and it's not fixed there. The PRs you cite deal with `tools/rosconsole/include/ros/console.h` and `include/ros/console.h` but the bug is in `include/rclcpp/logging.hpp`. I was actually compiling to write a PR to `rclcpp`. I see, that the issue was fixed in `master`. Should I close this PR?

**Comment by galou** [comment]
How do you ask for a backport?

**Comment by henningkayser** [comment]
> How do you ask for a backport?

We use the backport labels for that. I tagged this with `backport-galactic`

**Review by henningkayser — APPROVED** [review]

**Comment by henningkayser** [comment]
I agree with @v4hn that the real issue is upstream and should be fixed there. This change still makes sense to me, stream or no stream doesn't make a difference imo.

**Comment by galou** [comment]
@henningkayser thanks for the hint about labels. My question is now, how do you add a label?

**Comment by vatanaksoytezer** [comment]
> @henningkayser thanks for the hint about labels. My question is now, how do you add a label?

As far as I know only core contributors and maintainers can add labels for this repository.

**Comment by henningkayser** [comment]
@Mergifyio backport galactic

**Pull request closed without merging**
