### PR TITLE
Fix the `margin` argument for joint bounds checking

### LINKED ISSUE #2090: The `margin` argument to satisfiesVelocityBounds() is reversed
### Description

See https://github.com/ros-planning/moveit2/blob/4d3420cca312b51073d78df909293380fe73a2ff/moveit_core/robot_model/src/joint_model.cpp#L121

```
bool JointModel::satisfiesVelocityBounds(const double* values, const Bounds& other_bounds, double margin) const
{
  for (std::size_t i = 0; i < other_bounds.size(); ++i)
  {
    if (other_bounds[i].max_velocity_ + margin < values[i])
    {
      return false;
```

I think this should be:

```
bool JointModel::satisfiesVelocityBounds(const double* values, const Bounds& other_bounds, double margin) const
{
  for (std::size_t i = 0; i < other_bounds.size(); ++i)
  {
    if (other_bounds[i].max_velocity_ margin < values[i] + margin)
    {
      return false;
```

### PR DESCRIPTION
**Pull request by SuyashSapkal**
### Description

Removed `margin` argument when checking bounds. 
Raising a new PR with `remove_margin_arg` branch.

Fixes #2090

### Checklist
- [x] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] Extend the tutorials / documentation [reference](http://moveit.ros.org/documentation/contributing/)
- [ ] Document API changes relevant to the user in the [MIGRATION.md](https://github.com/ros-planning/moveit2/blob/main/MIGRATION.md) notes
- [ ] Create tests, which fail without this PR [reference](https://moveit.picknik.ai/humble/doc/examples/tests/tests_tutorial.html)
- [ ] Include a screenshot if changing a GUI
- [ ] While waiting for someone to review your request, please help review [another open pull request](https://github.com/ros-planning/moveit2/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Comment by AndyZe** [comment]
Now we can get into the nitty gritty of these CI failures  :+1:

Looking at the CI logs, there are some more places to remove the `margin` arg:

```
   /home/runner/work/moveit2/moveit2/.work/target_ws/src/moveit2/moveit_planners/ompl/ompl_interface/src/parameterization/model_based_state_space.cpp:203:59: error: no matching function for call to ‘moveit::core::JointModelGroup::satisfiesPositionBounds(double* const&, const JointBoundsVector&, double) const’
    203 |   return spec_.joint_model_group_->satisfiesPositionBounds(state->as<StateType>()->values, spec_.joint_bounds_,
        |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    204 |                                                            std::numeric_limits<double>::epsilon());
```

Note you can run the tests locally with `colcon test`

**Comment by SuyashSapkal** [comment]
I'll try to list down all the **function definitions** where I made changes and the **function calls** for those specific functions. 
Try to make changes there and make some commits. 

I think this will take some time but we can ensure that the function calls are done properly with the new argument changes.

Also, is there a way I can run these tests locally first then push the changes?

**Comment by SuyashSapkal** [comment]
Do we have any documentation for `colcon test` that I can refer?

**Comment by AndyZe** [comment]
TBH I don't think you will need to know anything more than `colcon build` and `colcon test --packages-select your_package_name`. Otherwise, I'd just google it

**Comment by SuyashSapkal** [comment]
I am getting like this when I try to run the command
image

**Comment by AndyZe** [comment]
That's definitely the right command. I just tested it. Are you sourced correctly? Does `colcon build` work?

**Comment by SuyashSapkal** [comment]
That doesn't work either. I have tried using it in both `moveit_core` directory and also in the main directory

**Comment by AndyZe** [comment]
You should run `colcon build` from the root of your workspace. For me, I run it from `~/ws_ros2` and the moveit2 repo is in `~/ws_ros2/src/moveit2`.

Yeah, it sounds like you are missing something basic in your setup. I'm working on rebasing this and possibly fixing some of the CI issues. Thanks for the work so far.

**Comment by AndyZe** [comment]
So, if we remove `margin` completely, it gets very deep into some OMPL changes. I don't want to mess with things at that level so I went ahead and reverted much of the previous work. With the latest commit, I just fixed the sign of `margin`. Let's see if this passes CI.

**Comment by SuyashSapkal** [comment]
So as per the last commit, we are not making any argument changes right?

So should I pick up a new issue? or we still have some changes to be done on this?

**Comment by AndyZe** [comment]
IMO this is done. Removing that argument completely got too deep in the codebase

**Review by AndyZe — APPROVED** [review]

**Comment by henningkayser** [comment]
@SuyashSapkal it looks like you force pushed a branch that is based on humble. This is why this PR is showing so many conflicts. Could you rebase your fix onto the latest main branch and push again?

**Comment by SuyashSapkal** [comment]
Ok sure

**Pull request merged**
