### PR TITLE
Reduce warnings

### PR DESCRIPTION
**Pull request by ahcorde**
Removing coma:

 - MOVEIT_CLASS_FORWARD 
 - MOVEIT_STRUCT_FORWARD

### CODE REVIEW

**Comment by mlautman** [comment]
Repo wide changes that are quick and easy to review are the best :)

Approved. Can you look into the reason travis is failing? Once we pass travis we can merge
```
CMake Error at CMakeLists.txt:32 (find_package):
  By not providing "Findoctomap.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "octomap", but
  CMake did not find one.
  Could not find a package configuration file provided by "octomap" with any
  of the following names:
    octomapConfig.cmake
    octomap-config.cmake
  Add the installation prefix of "octomap" to CMAKE_PREFIX_PATH or set
  "octomap_DIR" to a directory containing one of the above files.  If
  "octomap" provides a separate development package or SDK, be sure it has
  been installed.
```

**Comment by anasarrak** [comment]
@mlautman Can you relaunch the CI? I just lauched it locally and Im not getting any error there

```bash
Test blacklist: 
colcon test
colcon test --merge-install --packages-skip --event-handlers desktop_notification- status- 2>/dev/null
Starting >>> eigen_stl_containers
Starting >>> random_numbers
Starting >>> octomap-distribution
Finished <<< random_numbers [0.04s]
Finished <<< eigen_stl_containers [0.05s]
Starting >>> geometric_shapes
Finished <<< geometric_shapes [0.40s]
Finished <<< octomap-distribution [5.13s]

Summary: 4 packages finished [5.29s]
  1 package had stderr output: octomap-distribution
colcon test-results
Summary: 64 tests, 0 errors, 0 failures, 0 skipped
No warnings. Great!

```

**Comment by JafarAbdi** [comment]
lines '69` and `123` in `moveit_core/constraint_samplers/test/pr2_arm_kinematics_plugin.h` have commas that need to be removed

**Comment by henningkayser** [comment]
@ahcorde Thanks, could you also fix the other line @JafarAbdi mentioned? Then I would merge this PR.

**Comment by ahcorde** [comment]
sorry, I forgot it

**Comment by henningkayser** [comment]
@ahcorde Thanks!

**Pull request merged**
