### PR TITLE
Refactor and open the Python interface of planning_interface module

### PR DESCRIPTION
**Pull request by larrylu0426**
Abstract:
Replace the Python binding method based on boost_python in the existed code with pybind11. 

Main Idea:
To keep the existed function no changed, and use the inheritance method(seen in move_group_interface.cpp) to wrap the existed C++ APIs.

Contributions:
1. Replace boost python with pybind11, and keep the name and style of existed APIs as stable as possible;
2. Adapt the old ROS1-related codes;
3. Open both C++  and Python APIs about robot interface;
4. Open and refactor the Python APIs about rclcpp interface/move_group interface/planning_scene interface.

### CODE REVIEW

**Comment by mamoll** [comment]
@peterdavidfagan's current Google Summer of Code project also updates the python bindings using pybind11. See https://github.com/peterdavidfagan/moveit2/tree/moveit_py_dev

**Comment by larrylu0426** [comment]
> @peterdavidfagan's current Google Summer of Code project also updates the python bindings using pybind11. See https://github.com/peterdavidfagan/moveit2/tree/moveit_py_dev

Hi @mamoll , I have discussed with Peter. Firstly, for Python developers, the Planning Python APIs have already been blanked for a long time. I'm a newer of moveit2, and I did this work in my own project. Without the know of the whole developing plan, I submitted this PR just for refactoring the existed and out-of-date codes in the repo. As a software engineering student, I totally agree with you that we don't need do the same thing as twice. And I must to admit that this PR contains too many changes of code. It's too hard to review and test. My opinion is that if the requirements of supporting Python's API is necessary, we can try to merge this PR into main branch, after all, this PR doesn't block any existed function or API. When Peter's work done, the Python-related codes should be removed because the repo should be clear and tight. 😄 I love to contribute all for the moveit2, and I would like to follow your expert knowledge to do more 😉

**Comment by peterdavidfagan** [comment]
Hi @larrylu0426, 

In the weekly MoveIt community meeting this was briefly discussed. I agreed to perform a first pass and test all your changes so I will look to do so by this weekend. I also will be writing a concept article to explain differences between the legacy Python API and the one I am developing. 

@mamoll my understanding of the current status is that I will review the above changes which port much of the older Python API to MoveIt2. It was mentioned on our last call that potentially both Python libraries `moveit_commander` and `moveit_py` could be supported for some time. My opinion is in the long run one Python library should be present in the project. It may be that we transition users to using `moveit_py` in the long run as it directly binds much of the functionalities of MoveIt2. 

@larrylu0426 has already agreed/expressed interest in being involved in testing `moveit_py`, I think it would also be great to have his involvement in further developments after the first release of `moveit_py` is completed.

**Comment by larrylu0426** [comment]
> Hi @larrylu0426, 
> 
> 
> 
> In the weekly MoveIt stand up meeting this was briefly discussed. I agreed to perform a first pass and test all your changes so I will look to do so by this weekend. I also will be writing a concept article to explain differences between the legacy Python API and the one I am developing. 
> 
> 
> 
> @mamoll my understanding of the current status is that I will review the above changes which port much of the older Python API to MoveIt2. It was mentioned on our last call that potentially both Python libraries `moveit_commander` and `moveit_py` could be supported for some time. My opinion is in the long run one Python library should be present in the project. It may be that we transition users to using `moveit_py` in the long run as it directly binds much of the functionalities of MoveIt2. 
> 
> 
> 
> @larrylu0426 has already agreed/expressed interest in being involved in testing `moveit_py`, I think it would also be great to have his involvement in further developments after the first release of `moveit_py` is completed.

Totally agree with you! I have already found that many functions should be supported on the Python platform, such as collision avoidance. I will continue to work on this transition progress. We can corporate together to accurate the development of moveit_py. We have a same goal to make the moveit2 better 😁

**Comment by mamoll** [comment]
> We can corporate together to accurate the development of moveit_py. We have a same goal to make the moveit2 better 😁

Great! I just wanted to make sure that we avoid duplicate work. I trust that @peterdavidfagan's mentors, @henningkayser and @v4hn, are also keeping an eye on this.

**Comment by larrylu0426** [comment]
I have seen the conflicts. I will solve them recently. :)

**Comment by im-renpei** [comment]
Hi @larrylu0426 , I'm very excited to see your project. Do you have relevant demos or scripts to use these python interfaces?

**Comment by larrylu0426** [comment]
> 



> Hi @larrylu0426 , I'm very excited to see your project. Do you have relevant demos or scripts to use these python interfaces?

Hi @im-renpei , thanks for your attention. This PR just opens original and existed Python APIs. If you want to use them, you can see the WIKI pages of moveit1. An easy way to use Python APIs is trying the moveit_commander. To be honest, the opened Python APIs are following the old style. I'd like to introduce a more completed binding work: moveit_py by@peterdavidfagan. And I will focus on the developing of moveit_py. This PR, in my opinion, just a transition to wait moveit_py to be released. When it's ready, I think the old Python APIs will be removed to keep the project more clear. :)

**Comment by im-renpei** [comment]
Hi Larry @larrylu0426 , thanks for the suggestion. I will try moveit_py later.

**Comment by larrylu0426** [comment]
Hi @peterdavidfagan , conflicts have been removed :)

**Comment by peterdavidfagan** [comment]
> Hi @peterdavidfagan , conflicts have been removed :)

Thanks @larrylu0426, I will continue my review shortly, since yesterday I have been sick but I am hoping to be recovered enough to work from tomorrow.

**Comment by larrylu0426** [comment]
Hi @peterdavidfagan , I think that the review of this PR may cost we so much time due to the long change file list. And the moveit_py will be merged soon. This PR is closed.

**Comment by peterdavidfagan** [comment]
Hi @larrylu0426, 

Apologies I was sick last week so this got slightly delayed. 

Are you sure you wish to close the pr? There were many valuable changes made here. I am still happy to take the time to perform an initial review of the code.

**Comment by larrylu0426** [comment]
> Hi @larrylu0426, 
> 
> 
> 
> Apologies I was sick last week so this got slightly delayed. 
> 
> 
> 
> Are you sure you wish to close the pr? There were many valuable changes made here. I am still happy to take the time to perform an initial review of the code.

I'm sorry to hear that. The motivation of closing this PR is that I have seen the future of moveit_py. I think the most valuable thing I can do is that to make moveit_py more complete. The content in this PR can be found in my forked repo. So closing this PR is reasonable from my side.

**Comment by peterdavidfagan** [comment]
Thanks @larrylu0426. 

Ok understood and also thank you @larrylu0426 for seeing the potential in moveit_py. 

I am preparing api documentation for moveit_py this week. I will hopefully look to open a pr for the first release soon. Maybe you would like to join one of the next meetings we have about the library to stay up-to-date (and prevent duplicated work)? 

Your contributions would certainly be welcomed. One thing to note is that I need to keep a clear distinction between my work on moveit_py for GSoC and any external contributions. 

In anycase, I'll look to get docs and tests complete so we can release in the upcoming weeks.

**Pull request closed without merging**
