### PR TITLE
Update Maintainers of MoveIt package

### PR DESCRIPTION
**Pull request by davetcoleman**
I'm getting a lot of noisy emails from Jenkins such as:

>Build failed in Jenkins: Fdev__moveit__ubuntu_focal_amd64 #148

But I do not have bandwidth for this anymore. I'm also guessing @mikeferguson @IanTheEngineer @130s are not looking at this either, since we have not seen them in a long time.

I'd like to instead replace us with @henningkayser @tylerjw who are very actively involved.

I've also added myself as an author of MoveIt, which is mostly an ego thing that I'm fine removing also if it is judged my involvement at Willow Garage since before MoveIt was released as beta is not enough. I'm cool either way but this is clearly my preference.

### CODE REVIEW

**Review by tylerjw — APPROVED** [review]

**Review by 130s — APPROVED** [review]
Thanks.

If this would stop the notification from jenkins that'll be great too (my impression from the last I tried to do that a few years ago, updating package.xml may have not been enough though).

**Comment by mikeferguson** [comment]
Yeah - that fetchrobotics email hasn't worked in about 4 years now...

**Comment by mikeferguson** [comment]
> If this would stop the notification from jenkins that'll be great too (my impression from the last I tried to do that a few years ago, updating package.xml may have not been enough though).

If I recall correctly, you have to do a release as well to get the buildfarm to fully update

**Comment by henningkayser** [comment]
Makes sense to me. Shouldn't this be changed for the other `package.xml` files as well?

**Review by v4hn — APPROVED** [review]
> Makes sense to me. Shouldn't this be changed for the other package.xml files as well?

Yes, but it depends on Dave's preferences of course. @davetcoleman Hope you got the cycles to clean these entries consistently across all packages. You probably want to have similar changes in the moveit repository as well?

It makes sense to add you as an author in the meta-package. You are listed as author of MSA already which is a part of the stack.

**Comment by davetcoleman** [comment]
@v4hn can't tell if you're being sarcastic?

It would be great to have all the package.xml files updated. I did this edit through the Github webpage editor to address the specific issue of emails I was getting, it's a bit tougher for me to edit other instances as I don't have the code checked out.

**Comment by v4hn** [comment]
> can't tell if you're being sarcastic?

I'm not. it's entirely your decision on where you want to be listed.
I'm surprised this is still not merged.

It would be great if you could go through the packages systematically and adapt the maintainers as you did here.
`git clone` + `grep` takes something like 5 minutes.
If you can't do it, I'm also ok with merging this standalone.

**Comment by henningkayser** [comment]
I pushed a commit that
    * Removes Dave's maintainer entries with with Tyler,Henning
    * Adds Dave as author to moveit_core, moveit_ros
    * Adds missing authors to moveit_common, run_move_group, run_moeit_cpp
    * Removes entries of inactive maintainers

I would still like to make the entries more accurate from PickNik's side (add more of Jafar, Andy, hopefully soon Vatan), but we can still update these later.

**Comment by henningkayser** [comment]
xmllint wasn't happy with the changes. so I disabled the xml schema for the "broken" files in 5904793 for better diff readability.
#779 adds the ROS format 3 schema and fixes it for all `package.xml` files.

**Review by tylerjw — APPROVED** [review]

**Pull request merged**
