### PR TITLE
(moveit_py) node can have multiple param files

### PR DESCRIPTION
**Pull request by MatthijsBurgh**
### Description

A node is often started with multiple param files. Using `list.index` only returns the first occurrence. The new code searches for all occurrences.

### Checklist
- [x] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [x] Extend the tutorials / documentation [reference](http://moveit.ros.org/documentation/contributing/)
- [x] Document API changes relevant to the user in the [MIGRATION.md](https://github.com/ros-planning/moveit2/blob/main/MIGRATION.md) notes
- [x] Create tests, which fail without this PR [reference](https://moveit.picknik.ai/humble/doc/examples/tests/tests_tutorial.html)
- [x] Include a screenshot if changing a GUI
- [x] While waiting for someone to review your request, please help review [another open pull request](https://github.com/ros-planning/moveit2/pulls) to support the maintainers

Please backport to iron and rolling.

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Comment by MatthijsBurgh** [comment]
@peterdavidfagan any changes I need to make to this PR? Or is it ready for review?

**Comment by peterdavidfagan** [comment]
Hey @MatthijsBurgh, 

This looks good to me, thank you for this contribution. 

I have a paper deadline for October 10th, once this passes I'll test the above changes on my side.

**Comment by peterdavidfagan** [comment]
It has been a while since I looked at this but below is my understanding. 

> why we can't simply forward all the launch arguments blindly

**Short Answer** 
The MoveItPy instance in a given executable is not itself an instance of  and rclpy Node. I haven't delved into the rclpy codebase too much but I suspect somewhere they must also parse params from the command line arguments. I might be wrong on this but when a Node automatically works it due to logic implemented in rclpy and rclcpp.


**Long Answer**
The python launch scripts and in particular `launch_ros.actions.Node`, constructs a command to start a process for a given executable. Part of this process is constructing the ros_specific_arguments. For python executables (as is the case with this library), the python script gets executed with specific arguments which need to be parsed as the `MoveItPy` instance is not itself a Node but rather an object that spins and interfaces with moveit_cpp.

If the user themselves don't pass a config dict from MoveItConfigsBuilder, the parameters are automatically taken from the cli args as seen `[here](https://github.com/ros-planning/moveit2/blob/e7577cabc75dc1e48e90dec2ecf6ed357d03896b/moveit_py/src/moveit/moveit_ros/moveit_cpp/moveit_cpp.cpp#L65)`.

The logic for constructing cmd arguments from parameters can be found [here](https://github.com/ros2/launch_ros/blob/bc609787102ae1c0b8ad2ee9dbecf0165a9108a2/launch_ros/launch_ros/actions/node.py#L465C31-L465C31). This same script provides comments for how the node parameters are parsed etc.

**Comment by peterdavidfagan** [comment]
@MatthijsBurgh I am testing your changes now, thanks for this contribution. Would you be up for performing an interactive rebase of your branch so it only contains the latest changes. It would be really nice for readability.

**Review by peterdavidfagan — APPROVED** [review]
Approving these changes, they accomplish the fix of ensuring multiple parameter files get parsed. While going through this PR other issues relating to parsing of parameters were encountered. Follow up work will address these issues.

**Comment by MatthijsBurgh** [comment]
I rebased this PR on main. Dropping the merge commit.

I do think we should merge this PR, not waiting on the other open issues.

**Comment by peterdavidfagan** [comment]
Agreed on the above.

**Comment by MatthijsBurgh** [comment]
P.S. Do I still need approval to run workflows as I am still a first time contributor. Since this PR isn't merged yet? Or are your workflow settings strict that at all time outside contributors need approval. In that case, you maybe want to relax that. As that would speed up the process a little bit.

**Comment by peterdavidfagan** [comment]
Yeah the workflows usually require a maintainer to approve. I think there are also costs associated with these workflows so it might be problematic to run them for every update to a pr.

**Comment by MatthijsBurgh** [comment]
@peterdavidfagan friendly ping to trigger CI :)

**Comment by peterdavidfagan** [comment]
Hey @MatthijsBurgh I don't have access unfortunately but @henningkayser or @sjahr may be able to help as they are maintainers and should have access. I have been using your code and all is good hopefully these changes can be merged soon.

**Review by sjahr — APPROVED** [review]

**Comment by MatthijsBurgh** [comment]
@sjahr It seems the CI issues are not related to the changes in this PR. Correct?

**Pull request merged**
