### PR TITLE
adds const to moveit_core/distance_field issue 879

### PR DESCRIPTION
**Pull request by danielcorona19**
### Description

Added const keyword to function parameters in moveit_core/distance_field. This PR is related to #879 

### Checklist
- [ ] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] Extend the tutorials / documentation [reference](http://moveit.ros.org/documentation/contributing/)
- [ ] Document API changes relevant to the user in the [MIGRATION.md](https://github.com/ros-planning/moveit2/blob/main/MIGRATION.md) notes
- [ ] Create tests, which fail without this PR [reference](https://moveit.picknik.ai/humble/doc/examples/tests/tests_tutorial.html)
- [ ] Include a screenshot if changing a GUI
- [ ] While waiting for someone to review your request, please help review [another open pull request](https://github.com/ros-planning/moveit2/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Review by sea-bass — COMMENTED** [review]
Can you run `pre-commit run -a` on this branch to fix the formatting failure? Looks great otherwise!

**Review by sea-bass — APPROVED** [review]

**Comment by sea-bass** [comment]
> Quick hold-up before merging. Do we event want to add cost for per-value parameters? There has been a related discussion here #2119 and we should follow a consistent style.

Good call -- particularly the opinion in https://github.com/ros-planning/moveit2/pull/2119#issuecomment-1594866993 is that `const` for simple value parameters doesn't really do much. I'm in favor of closing this for consistency and to reduce change for the sake of change?

**Comment by danielcorona19** [comment]
I just did this PR because I am a new contributor and I would like to understand the procedure of contributing to the MoveIt project. I wasn't able to correct the clang-format because the `pre-commit run -a` wasn't automatically correcting the format.

**Comment by sea-bass** [comment]
No worries @danielcorona19 -- I think we'll go ahead and close this one because of https://github.com/ros-planning/moveit2/pull/2119#issuecomment-1594866993.

Thank for your working on this and we look forward to your next contiribution(s) -- here are many other "good first issue" type issues to try out!

**Pull request closed without merging**
