### PR TITLE
[pilz_industrial_motion_planner] Add includes

### PR DESCRIPTION
**Pull request by galou**
Signed-off-by: Gaël Écorchard <gael.ecorchard@cvut.cz>

### Description

Add missing `#include`.

### Checklist
- [x] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] Extend the tutorials / documentation [reference](http://moveit.ros.org/documentation/contributing/)
- [x] Document API changes relevant to the user in the [MIGRATION.md](https://github.com/ros-planning/moveit/blob/master/MIGRATION.md) notes
- [ ] Create tests, which fail without this PR [reference](https://ros-planning.github.io/moveit_tutorials/doc/tests/tests_tutorial.html)
- [ ] Include a screenshot if changing a GUI
- [ ] While waiting for someone to review your request, please help review [another open pull request](https://github.com/ros-planning/moveit/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Review by henningkayser — COMMENTED** [review]
I don't really get why these would be needed. Did you run into build issues? At least we shouldn't have to include them inside both header and source file.

**Comment by galou** [comment]
I just add all includes that I cite in the given file, i.e. possibly repeating an include in the source and associated header files. Just close the PR if you don't want this.

**Comment by tylerjw** [comment]
@ChrisThrasher what do you think of this PR? It doesn't seem to harm anything but also I'm not sure it is necessary. Should we decide on a policy of when you should include a header and where?

**Comment by ChrisThrasher** [comment]
Are these additional headers necessary to fix something?

**Comment by galou** [comment]
As stated, these includes are not strictly necessary.

**Comment by tylerjw** [comment]
@galou thank you for the clarification. I'm going to close this for now. We should write a policy around what and when we include various things. There are many opinions about how we should use includes and we lack consistency.

**Pull request closed without merging**
