### PR TITLE
moveit servo: fix constructing duration from double & fix bug in insertRedundantPointsIntoTrajectory function

### PR DESCRIPTION
**Pull request by JafarAbdi**
### Description

Fixes two bugs:
1- Constructing a duration from a double by using `rclcpp::Duration::from_seconds` otherwise the values will cast to int
2- In `insertRedundantPointsIntoTrajectory` function we were starting from the third point, not the second one, so I fixed the index in the for-loop

### Checklist
- [ ] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] Extend the tutorials / documentation [reference](http://moveit.ros.org/documentation/contributing/)
- [ ] Document API changes relevant to the user in the [MIGRATION.md](https://github.com/ros-planning/moveit/blob/master/MIGRATION.md) notes
- [ ] Create tests, which fail without this PR [reference](https://ros-planning.github.io/moveit_tutorials/doc/tests/tests_tutorial.html)
- [ ] Include a screenshot if changing a GUI
- [ ] While waiting for someone to review your request, please help review [another open pull request](https://github.com/ros-planning/moveit/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Review by AndyZe — APPROVED** [review]
Thanks @JafarAbdi! Looks good to me.

**Comment by AndyZe** [comment]
Before merging, can you try setting `use_gazebo=false` in this config file? I think it was used as a Band-Aid fix for the issue you uncovered but we shouldn't need it.

https://github.com/ros-planning/moveit2/blob/main/moveit_ros/moveit_servo/config/panda_simulated_config.yaml

**Comment by JafarAbdi** [comment]
> Before merging, can you try setting `use_gazebo=false` in this config file? I think it was used as a Band-Aid fix for the issue you uncovered but we shouldn't need it.
> 
> https://github.com/ros-planning/moveit2/blob/main/moveit_ros/moveit_servo/config/panda_simulated_config.yaml

I changed it to false, the robot is working without any problem

**Comment by JafarAbdi** [comment]
> Before merging, can you try setting `use_gazebo=false` in this config file? I think it was used as a Band-Aid fix for the issue you uncovered but we shouldn't need it.
> 
> https://github.com/ros-planning/moveit2/blob/main/moveit_ros/moveit_servo/config/panda_simulated_config.yaml

I changed it to false, the robot is working without any problem

**Pull request merged**
