### PR TITLE
Add comment when formatting fails

### PR DESCRIPTION
**Pull request by tylerjw**
### Description

Here is a small addition to the Format checking Action to post a comment instructing users on how to fix the formatting issues.

### CODE REVIEW

**Review by henningkayser — APPROVED** [review]
Sweet!

**Review by rhaschke — COMMENTED** [review]
Cool. How does it look like? I guess that's creating a badge on github?

**Comment by tylerjw** [comment]
I think it replies to the pull request when this happens.

**Comment by rhaschke** [comment]
> I think it replies to the pull request when this happens.

That's what I thought too. Please give it a try to confirm and validate.

**Comment by tylerjw** [comment]
This basically won't work with forked repos (and therefore not with our model, closing).  :(

**Pull request closed without merging**
