### PR TITLE
Change KDL IK plugin joint weight parameters specification

### PR DESCRIPTION
**Pull request by sea-bass**
### Description

This is a potential fix for #2749.

It changes the KDL parameters introduced in https://github.com/ros-planning/moveit2/pull/1671 from:

```yaml
panda_arm:
  kinematics_solver: "kdl_kinematics_plugin/KDLKinematicsPlugin"
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.05

  joints: ["joint1", "joint2", "joint3", "joint4", "joint5", "joint6"]
  # Default weight for joints is 1.0 
  joint1:
    weight: 2.0
  joint5:
    weight: 1.5
```

to 

```yaml
panda_arm:
  kinematics_solver: "kdl_kinematics_plugin/KDLKinematicsPlugin"
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.05

  joints: ["joint1", "joint2", "joint3", "joint4", "joint5", "joint6"]
  # Default weight for joints is 1.0 
  weights:
    joint1:
      value: 2.0
    joint5:
      value: 1.5
```

### Checklist
- [x] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] Extend the tutorials / documentation [reference](http://moveit.ros.org/documentation/contributing/)
- [ ] Document API changes relevant to the user in the [MIGRATION.md](https://github.com/ros-planning/moveit2/blob/main/MIGRATION.md) notes
- [ ] Create tests, which fail without this PR [reference](https://moveit.picknik.ai/humble/doc/examples/tests/tests_tutorial.html)
- [x] Include a screenshot if changing a GUI
- [x] While waiting for someone to review your request, please help review [another open pull request](https://github.com/ros-planning/moveit2/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Comment by sea-bass** [comment]
Ugh, seems like MoveIt Setup Assistant has some failures due to the addition of the nonzero velocity here: https://github.com/ros-planning/moveit_resources/pull/198/files

**Review by sjahr — APPROVED** [review]
Do we need to update some moveit_resoures repositories?

**Comment by sea-bass** [comment]
> Do we need to update some moveit_resources packages?

Actually, no, because none of the example configs even sets joint weights in the first place!

But ler's not merge this in yet, as we could also opt to fix generate_parameter_library

**Comment by rhaschke** [comment]
Why don't you simply use a map from joint name to weight (instead of an additional indirection layer):
```yaml
  weights:
    joint1: 2.0
    joint5: 1.5
```

**Comment by sea-bass** [comment]
> Why don't you simply use a map from joint name to weight (instead of an additional indirection layer):
> 
> ```yaml
>   weights:
>     joint1: 2.0
>     joint5: 1.5
> ```

That does sound good, but I'm not sure if `generate_parameter_library` supports doing this at the moment. Looking at the examples: https://github.com/PickNikRobotics/generate_parameter_library?tab=readme-ov-file#mapped-parameters, seems like there has to be a field underneath the mapped parameters.

**Comment by rhaschke** [comment]
> I'm not sure if `generate_parameter_library` supports doing this at the moment.

If it doesn't, you probably should fix that library. A library implementation shouldn't impose constraints on the kind of parameter structures available.

**Comment by Abishalini** [comment]
If humble CI jobs pass, would it make sense to merge this while a fix to `generate_param_library` is being worked on?
This would unblock other PRs in the repo

**Comment by sea-bass** [comment]
Seems there is interest in fixing CI for now, so will open up https://github.com/ros-planning/moveit2/issues/2756 and we'll make sure we get that in for the next MoveIt 2 release.

**Comment by sea-bass** [comment]
Update: I think I fixed `generate_parameter_library` to be able to keep the old syntax: https://github.com/PickNikRobotics/generate_parameter_library/pull/185

**Comment by gavanderhoorn** [comment]
@sea-bass: could the branch be deleted?

**Pull request closed without merging**
