### PR TITLE
Update .pre-commit-config.yaml

### PR DESCRIPTION
**Pull request by mosfet80**
Updated codespell

### Description

Please explain the changes you made, including a reference to the related issue if applicable

### Checklist
- [x] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] Extend the tutorials / documentation [reference](http://moveit.ros.org/documentation/contributing/)
- [ ] Document API changes relevant to the user in the [MIGRATION.md](https://github.com/ros-planning/moveit2/blob/main/MIGRATION.md) notes
- [ ] Create tests, which fail without this PR [reference](https://moveit.picknik.ai/humble/doc/examples/tests/tests_tutorial.html)
- [ ] Include a screenshot if changing a GUI
- [ ] While waiting for someone to review your request, please help review [another open pull request](https://github.com/ros-planning/moveit2/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Comment by marioprats** [comment]
Looks like the new version is catching a bunch of new spelling issues.
Would you mind fixing them as part of this PR so that the checks pass?
If you can't please let me know and I'll take it over. Thanks!

**Comment by marioprats** [comment]
Here's a link to the issues found by the format check: https://github.com/ros-planning/moveit2/actions/runs/6453757742/job/17517921805?pr=2382#step:5:181

**Comment by Shobuj-Paul** [comment]
This has already been fixed by #2465 
Sorry @mosfet80 , didn't notice this PR before putting mine in.

**Comment by marioprats** [comment]
Thanks @mosfet80 and @Shobuj-Paul!
I'm closing this PR then.

**Pull request closed without merging**
