### PR TITLE
Add ABI check to Foxy

### PR DESCRIPTION
**Pull request by vatanaksoytezer**

### CODE REVIEW

**Review by tylerjw — APPROVED** [review]

**Comment by henningkayser** [comment]
@vatanaksoytezer should we really merge this? The build job took over 3 hours. Is there any way to reduce this by only checking the diff or so?

**Comment by vatanaksoytezer** [comment]
> @vatanaksoytezer should we really merge this? The build job took over 3 hours. Is there any way to reduce this by only checking the diff or so?

I should investigate. Can we re-run the build, caching might help this significantly.

**Comment by henningkayser** [comment]
@vatanaksoytezer should we port this to Galactic as well?

**Comment by vatanaksoytezer** [comment]
> @vatanaksoytezer should we port this to Galactic as well? It's still 2.5h, btw

Yes, but it's still taking more than 2.5 hours, should we investigate or we are fine with this?

**Comment by henningkayser** [comment]
I converted this to draft, we need to reduce the build time before getting this merged

**Comment by tylerjw** [comment]
Created issue for tracking resuming this. Closing for now.

**Pull request closed without merging**
