### PR TITLE
Move clang tidy under galactic-ci

### PR DESCRIPTION
**Pull request by vatanaksoytezer**
As per discussion in #651 I think it is a good idea to enforce clang-tidy and move it under galactic-ci job (which is enforced).

Update: @henningkayser or any admin needs to change the required jobs before merging this.

### CODE REVIEW

**Comment by v4hn** [comment]
Thanks for the quick response on a side note!
The relevant job fails for unrelated reasons though...

**Comment by vatanaksoytezer** [comment]
> The relevant job fails for unrelated reasons though...

Yep unfortunately everything will fail in main branch until https://github.com/ros-planning/moveit2/pull/657 gets merged.

**Comment by henningkayser** [comment]
This is coming in a little late, but why shouldn't we run this on rolling-ci?

**Comment by vatanaksoytezer** [comment]
> This is coming in a little late, but why shouldn't we run this on rolling-ci?

rolling-ci is already slow with ccov (around 45 minutes each run). galactic-ci takes around 8 minutes and clang-tidy takes around 8 minutes itself. So we can run in parallel (53 + 8 vs 45 + 16).

**Review by henningkayser — APPROVED** [review]

**Pull request merged**
