### PR TITLE
WIP: Enable moveit_kinematics launch tests

### PR DESCRIPTION
**Pull request by sjahr**
### Description

Continued working on #212  to enable moveit_kinematics launch tests with ROS 2's [launch_testing](https://github.com/ros2/launch/tree/master/launch_testing).

### Checklist
- [ ] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [X] Fix test_kinematics_plugin
- [ ] Port fanuc-kdl.test
- [ ] Port fanuc-ikfast.test
- [ ] Port panda-kdl.test
- [ ] Port panda-ikfast.test

To build and run the tests:
1. Build package with testing enabled
```
colcon build --packages-select moveit_kinematics --cmake-args -DCMAKE_BUILD_TYPE=Release -BUILD_TESTING=true
```

2. Run the tests:
```
colcon test --packages-select moveit_kinematics
```

3. Show results
```
colcon test-result --all --verbose
```

### CODE REVIEW

**Comment by sjahr** [comment]
@JafarAbdi @henningkayser
When I am running the launch tests, KinematicsTest.unitIK tests fail for the fanuc_kdl_singular test. Do you have an idea why this is happening? Thanks in advance for your help!

**Comment by JafarAbdi** [comment]
> @JafarAbdi @henningkayser
> When I am running the launch tests, KinematicsTest.unitIK tests fail for the fanuc_kdl_singular test. Do you have an idea why this is happening? Thanks in advance for your help!

Do you mind sharing the logging outputs.?

**Comment by sjahr** [comment]
> > @JafarAbdi @henningkayser
> > When I am running the launch tests, KinematicsTest.unitIK tests fail for the fanuc_kdl_singular test. Do you have an idea why this is happening? Thanks in advance for your help!
> 
> Do you mind sharing the logging outputs.?

Not at all

```
ws_ros2$ colcon test-result --all --verbose
build/moveit_kinematics/Testing/20201125-1412/Test.xml: 4 tests, 0 errors, 1 failure, 0 skipped
- test_launch_fanuc-kdl-singular.test.py
  <<< failure message
    -- run_test.py: invoking following command in '/home/sebi/ws_ros2/build/moveit_kinematics/test':
     - /usr/bin/python3 -m launch_testing.launch_test /home/sebi/ws_ros2/src/moveit2/moveit_kinematics/test/launch/fanuc-kdl-singular.test.py --junit-xml=/home/sebi/ws_ros2/build/moveit_kinematics/test_results/moveit_kinematics/test_launch_fanuc-kdl-singular.test.py.xunit.xml --package-name=moveit_kinematics
    [INFO] [launch]: All log files can be found below /home/sebi/.ros/log/2020-11-25-15-12-03-859257-red-five-33687
    [INFO] [launch]: Default logging verbosity is set to INFO
    
    ----------------------------------------------------------------------
    Ran 0 tests in 0.000s
    
    OK
    Task exception was never retrieved
    future: <Task finished name='Task-9' coro=<LaunchService._process_one_event() done, defined at /opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py:271> exception=RuntimeError('Signal event received before subprocess transport available.')>
    Traceback (most recent call last):
      File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py", line 273, in _process_one_event
        await self.__process_event(next_event)
      File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py", line 293, in __process_event
        visit_all_entities_and_collect_futures(entity, self.__context))
      File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 38, in visit_all_entities_and_collect_futures
        sub_entities = entity.visit(context)
      File "/opt/ros/foxy/lib/python3.8/site-packages/launch/action.py", line 108, in visit
        return self.execute(context)
      File "/opt/ros/foxy/lib/python3.8/site-packages/launch/actions/opaque_function.py", line 75, in execute
        return self.__function(context, *self.__args, **self.__kwargs)
      File "/opt/ros/foxy/lib/python3.8/site-packages/launch/actions/execute_process.py", line 421, in __on_signal_process_event
        raise RuntimeError('Signal event received before subprocess transport available.')
    RuntimeError: Signal event received before subprocess transport available.
    [INFO] [test_kinematics_plugin-1]: process started with pid [33690]
    [test_kinematics_plugin-1] [==========] Running 8 tests from 1 test case.
    [test_kinematics_plugin-1] [----------] Global test environment set-up.
    [test_kinematics_plugin-1] [----------] 8 tests from KinematicsTest
    [test_kinematics_plugin-1] [ RUN      ] KinematicsTest.getFK
    [test_kinematics_plugin-1] [INFO] [1606313523.953146645] [test_kinematics_plugin]: Loading robot model from fanuc_kdl_singular.robot_description
    [test_kinematics_plugin-1] Parsing robot urdf xml string.
    [test_kinematics_plugin-1] [INFO] [1606313523.953755180] [moveit_rdf_loader.rdf_loader]: Loaded robot model in 0.000491034 seconds
    [test_kinematics_plugin-1] [INFO] [1606313523.953779746] [moveit_robot_model.robot_model]: Loading robot model 'fanuc'...
    [test_kinematics_plugin-1] [INFO] [1606313523.962252234] [test_kinematics_plugin]: Loading kdl_kinematics_plugin/KDLKinematicsPlugin
    [test_kinematics_plugin-1] Link base had 0 children
    [test_kinematics_plugin-1] Link link_1 had 1 children
    [test_kinematics_plugin-1] Link link_2 had 1 children
    [test_kinematics_plugin-1] Link link_3 had 1 children
    [test_kinematics_plugin-1] Link link_4 had 1 children
    [test_kinematics_plugin-1] Link link_5 had 1 children
    [test_kinematics_plugin-1] Link link_6 had 1 children
    [test_kinematics_plugin-1] Link tool0 had 0 children
    [test_kinematics_plugin-1] [INFO] [1606313523.963784707] [test_kinematics_plugin]: Loading kdl_kinematics_plugin/KDLKinematicsPlugin
    [test_kinematics_plugin-1] Link base had 0 children
    [test_kinematics_plugin-1] Link link_1 had 1 children
    [test_kinematics_plugin-1] Link link_2 had 1 children
    [test_kinematics_plugin-1] Link link_3 had 1 children
    [test_kinematics_plugin-1] Link link_4 had 1 children
    [test_kinematics_plugin-1] Link link_5 had 1 children
    [test_kinematics_plugin-1] Link link_6 had 1 children
    [test_kinematics_plugin-1] Link tool0 had 0 children
    [test_kinematics_plugin-1] [INFO] [1606313523.963845331] [test_kinematics_plugin]: Loading kdl_kinematics_plugin/KDLKinematicsPlugin
    [test_kinematics_plugin-1] Link base had 0 children
    [test_kinematics_plugin-1] Link link_1 had 1 children
    [test_kinematics_plugin-1] Link link_2 had 1 children
    [test_kinematics_plugin-1] Link link_3 had 1 children
    [test_kinematics_plugin-1] Link link_4 had 1 children
    [test_kinematics_plugin-1] Link link_5 had 1 children
    [test_kinematics_plugin-1] Link link_6 had 1 children
    [test_kinematics_plugin-1] Link tool0 had 0 children
    [test_kinematics_plugin-1] [       OK ] KinematicsTest.getFK (19 ms)
    [test_kinematics_plugin-1] [ RUN      ] KinematicsTest.randomWalkIK
    [test_kinematics_plugin-1] [       OK ] KinematicsTest.randomWalkIK (0 ms)
    [test_kinematics_plugin-1] [ RUN      ] KinematicsTest.unitIK
    [test_kinematics_plugin-1] /home/sebi/ws_ros2/src/moveit2/moveit_kinematics/test/test_kinematics_plugin.cpp:449: Failure
    [test_kinematics_plugin-1] Expected equality of these values:
    [test_kinematics_plugin-1]   error_code.val
    [test_kinematics_plugin-1]     Which is: -6
    [test_kinematics_plugin-1]   error_code.SUCCESS
    [test_kinematics_plugin-1]     Which is: 1
    [test_kinematics_plugin-1] Google Test trace:
    [test_kinematics_plugin-1] /home/sebi/ws_ros2/src/moveit2/moveit_kinematics/test/test_kinematics_plugin.cpp:509: 
    [test_kinematics_plugin-1] /home/sebi/ws_ros2/src/moveit2/moveit_kinematics/test/test_kinematics_plugin.cpp:449: Failure
    [test_kinematics_plugin-1] Expected equality of these values:
    [test_kinematics_plugin-1]   error_code.val
    [test_kinematics_plugin-1]     Which is: -6
    [test_kinematics_plugin-1]   error_code.SUCCESS
    [test_kinematics_plugin-1]     Which is: 1
    [test_kinematics_plugin-1] Google Test trace:
    [test_kinematics_plugin-1] /home/sebi/ws_ros2/src/moveit2/moveit_kinematics/test/test_kinematics_plugin.cpp:509: 
    [test_kinematics_plugin-1] /home/sebi/ws_ros2/src/moveit2/moveit_kinematics/test/test_kinematics_plugin.cpp:449: Failure
    [test_kinematics_plugin-1] Expected equality of these values:
    [test_kinematics_plugin-1]   error_code.val
    [test_kinematics_plugin-1]     Which is: -6
    [test_kinematics_plugin-1]   error_code.SUCCESS
    [test_kinematics_plugin-1]     Which is: 1
    [test_kinematics_plugin-1] Google Test trace:
    [test_kinematics_plugin-1] /home/sebi/ws_ros2/src/moveit2/moveit_kinematics/test/test_kinematics_plugin.cpp:509: 
    [test_kinematics_plugin-1] /home/sebi/ws_ros2/src/moveit2/moveit_kinematics/test/test_kinematics_plugin.cpp:449: Failure
    [test_kinematics_plugin-1] Expected equality of these values:
    [test_kinematics_plugin-1]   error_code.val
    [test_kinematics_plugin-1]     Which is: -6
    [test_kinematics_plugin-1]   error_code.SUCCESS
    [test_kinematics_plugin-1]     Which is: 1
    [test_kinematics_plugin-1] Google Test trace:
    [test_kinematics_plugin-1] /home/sebi/ws_ros2/src/moveit2/moveit_kinematics/test/test_kinematics_plugin.cpp:509: 
    [test_kinematics_plugin-1] /home/sebi/ws_ros2/src/moveit2/moveit_kinematics/test/test_kinematics_plugin.cpp:449: Failure
    [test_kinematics_plugin-1] Expected equality of these values:
    [test_kinematics_plugin-1]   error_code.val
    [test_kinematics_plugin-1]     Which is: -6
    [test_kinematics_plugin-1]   error_code.SUCCESS
    [test_kinematics_plugin-1]     Which is: 1
    [test_kinematics_plugin-1] Google Test trace:
    [test_kinematics_plugin-1] /home/sebi/ws_ros2/src/moveit2/moveit_kinematics/test/test_kinematics_plugin.cpp:509: 
    [test_kinematics_plugin-1] /home/sebi/ws_ros2/src/moveit2/moveit_kinematics/test/test_kinematics_plugin.cpp:449: Failure
    [test_kinematics_plugin-1] Expected equality of these values:
    [test_kinematics_plugin-1]   error_code.val
    [test_kinematics_plugin-1]     Which is: -6
    [test_kinematics_plugin-1]   error_code.SUCCESS
    [test_kinematics_plugin-1]     Which is: 1
    [test_kinematics_plugin-1] Google Test trace:
    [test_kinematics_plugin-1] /home/sebi/ws_ros2/src/moveit2/moveit_kinematics/test/test_kinematics_plugin.cpp:509: 
    [test_kinematics_plugin-1] /home/sebi/ws_ros2/src/moveit2/moveit_kinematics/test/test_kinematics_plugin.cpp:449: Failure
    [test_kinematics_plugin-1] Expected equality of these values:
    [test_kinematics_plugin-1]   error_code.val
    [test_kinematics_plugin-1]     Which is: -6
    [test_kinematics_plugin-1]   error_code.SUCCESS
    [test_kinematics_plugin-1]     Which is: 1
    [test_kinematics_plugin-1] Google Test trace:
    [test_kinematics_plugin-1] /home/sebi/ws_ros2/src/moveit2/moveit_kinematics/test/test_kinematics_plugin.cpp:509: 
    [test_kinematics_plugin-1] /home/sebi/ws_ros2/src/moveit2/moveit_kinematics/test/test_kinematics_plugin.cpp:449: Failure
    [test_kinematics_plugin-1] Expected equality of these values:
    [test_kinematics_plugin-1]   error_code.val
    [test_kinematics_plugin-1]     Which is: -6
    [test_kinematics_plugin-1]   error_code.SUCCESS
    [test_kinematics_plugin-1]     Which is: 1
    [test_kinematics_plugin-1] Google Test trace:
    [test_kinematics_plugin-1] /home/sebi/ws_ros2/src/moveit2/moveit_kinematics/test/test_kinematics_plugin.cpp:509: 
    [test_kinematics_plugin-1] /home/sebi/ws_ros2/src/moveit2/moveit_kinematics/test/test_kinematics_plugin.cpp:449: Failure
    [test_kinematics_plugin-1] Expected equality of these values:
    [test_kinematics_plugin-1]   error_code.val
    [test_kinematics_plugin-1]     Which is: -6
    [test_kinematics_plugin-1]   error_code.SUCCESS
    [test_kinematics_plugin-1]     Which is: 1
    [test_kinematics_plugin-1] Google Test trace:
    [test_kinematics_plugin-1] /home/sebi/ws_ros2/src/moveit2/moveit_kinematics/test/test_kinematics_plugin.cpp:509: 
    [test_kinematics_plugin-1] /home/sebi/ws_ros2/src/moveit2/moveit_kinematics/test/test_kinematics_plugin.cpp:449: Failure
    [test_kinematics_plugin-1] Expected equality of these values:
    [test_kinematics_plugin-1]   error_code.val
    [test_kinematics_plugin-1]     Which is: -6
    [test_kinematics_plugin-1]   error_code.SUCCESS
    [test_kinematics_plugin-1]     Which is: 1
    [test_kinematics_plugin-1] Google Test trace:
    [test_kinematics_plugin-1] /home/sebi/ws_ros2/src/moveit2/moveit_kinematics/test/test_kinematics_plugin.cpp:509: 
    [test_kinematics_plugin-1] /home/sebi/ws_ros2/src/moveit2/moveit_kinematics/test/test_kinematics_plugin.cpp:449: Failure
    [test_kinematics_plugin-1] Expected equality of these values:
    [test_kinematics_plugin-1]   error_code.val
    [test_kinematics_plugin-1]     Which is: -6
    [test_kinematics_plugin-1]   error_code.SUCCESS
    [test_kinematics_plugin-1]     Which is: 1
    [test_kinematics_plugin-1] Google Test trace:
    [test_kinematics_plugin-1] /home/sebi/ws_ros2/src/moveit2/moveit_kinematics/test/test_kinematics_plugin.cpp:509: 
    [test_kinematics_plugin-1] /home/sebi/ws_ros2/src/moveit2/moveit_kinematics/test/test_kinematics_plugin.cpp:449: Failure
    [test_kinematics_plugin-1] Expected equality of these values:
    [test_kinematics_plugin-1]   error_code.val
    [test_kinematics_plugin-1]     Which is: -6
    [test_kinematics_plugin-1]   error_code.SUCCESS
    [test_kinematics_plugin-1]     Which is: 1
    [test_kinematics_plugin-1] Google Test trace:
    [test_kinematics_plugin-1] /home/sebi/ws_ros2/src/moveit2/moveit_kinematics/test/test_kinematics_plugin.cpp:509: 
    [test_kinematics_plugin-1] [  FAILED  ] KinematicsTest.unitIK (2402 ms)
    [test_kinematics_plugin-1] [ RUN      ] KinematicsTest.searchIK
    [test_kinematics_plugin-1] [       OK ] KinematicsTest.searchIK (0 ms)
    [test_kinematics_plugin-1] [ RUN      ] KinematicsTest.searchIKWithCallback
    [test_kinematics_plugin-1] [       OK ] KinematicsTest.searchIKWithCallback (0 ms)
    [test_kinematics_plugin-1] [ RUN      ] KinematicsTest.getIK
    [test_kinematics_plugin-1] [INFO] [1606313526.365853891] [test_kinematics_plugin]: Loading kdl_kinematics_plugin/KDLKinematicsPlugin
    [test_kinematics_plugin-1] Link base had 0 children
    [test_kinematics_plugin-1] Link link_1 had 1 children
    [test_kinematics_plugin-1] Link link_2 had 1 children
    [test_kinematics_plugin-1] Link link_3 had 1 children
    [test_kinematics_plugin-1] Link link_4 had 1 children
    [test_kinematics_plugin-1] Link link_5 had 1 children
    [test_kinematics_plugin-1] Link link_6 had 1 children
    [test_kinematics_plugin-1] Link tool0 had 0 children
    [test_kinematics_plugin-1] [INFO] [1606313526.365921558] [test_kinematics_plugin]: searchIK
    [test_kinematics_plugin-1] [INFO] [1606313526.365927119] [test_kinematics_plugin]: searchIK
    [test_kinematics_plugin-1] [INFO] [1606313526.365935264] [test_kinematics_plugin]: Loading kdl_kinematics_plugin/KDLKinematicsPlugin
    [test_kinematics_plugin-1] Link base had 0 children
    [test_kinematics_plugin-1] Link link_1 had 1 children
    [test_kinematics_plugin-1] Link link_2 had 1 children
    [test_kinematics_plugin-1] Link link_3 had 1 children
    [test_kinematics_plugin-1] Link link_4 had 1 children
    [test_kinematics_plugin-1] Link link_5 had 1 children
    [test_kinematics_plugin-1] Link link_6 had 1 children
    [test_kinematics_plugin-1] Link tool0 had 0 children
    [test_kinematics_plugin-1] [INFO] [1606313526.365957476] [test_kinematics_plugin]: searchIKWithCallback
    [test_kinematics_plugin-1] [INFO] [1606313526.365961363] [test_kinematics_plugin]: searchIKWithCallback
    [test_kinematics_plugin-1] [INFO] [1606313526.365968687] [test_kinematics_plugin]: Loading kdl_kinematics_plugin/KDLKinematicsPlugin
    [test_kinematics_plugin-1] Link base had 0 children
    [test_kinematics_plugin-1] Link link_1 had 1 children
    [test_kinematics_plugin-1] Link link_2 had 1 children
    [test_kinematics_plugin-1] Link link_3 had 1 children
    [test_kinematics_plugin-1] Link link_4 had 1 children
    [test_kinematics_plugin-1] Link link_5 had 1 children
    [test_kinematics_plugin-1] Link link_6 had 1 children
    [test_kinematics_plugin-1] Link tool0 had 0 children
    [test_kinematics_plugin-1] [INFO] [1606313526.365988755] [test_kinematics_plugin]: getIK
    [test_kinematics_plugin-1] [INFO] [1606313526.365992953] [test_kinematics_plugin]: getIK
    [test_kinematics_plugin-1] [INFO] [1606313526.366000327] [test_kinematics_plugin]: Loading kdl_kinematics_plugin/KDLKinematicsPlugin
    [test_kinematics_plugin-1] Link base had 0 children
    [test_kinematics_plugin-1] Link link_1 had 1 children
    [test_kinematics_plugin-1] Link link_2 had 1 children
    [test_kinematics_plugin-1] Link link_3 had 1 children
    [test_kinematics_plugin-1] Link link_4 had 1 children
    [test_kinematics_plugin-1] Link link_5 had 1 children
    [test_kinematics_plugin-1] Link link_6 had 1 children
    [test_kinematics_plugin-1] Link tool0 had 0 children
    [test_kinematics_plugin-1] [       OK ] KinematicsTest.getIK (0 ms)
    [test_kinematics_plugin-1] [ RUN      ] KinematicsTest.getIKMultipleSolutions
    [test_kinematics_plugin-1] [       OK ] KinematicsTest.getIKMultipleSolutions (1 ms)
    [test_kinematics_plugin-1] [ RUN      ] KinematicsTest.getNearestIKSolution
    [test_kinematics_plugin-1] [       OK ] KinematicsTest.getNearestIKSolution (0 ms)
    [test_kinematics_plugin-1] [----------] 8 tests from KinematicsTest (2422 ms total)
    [test_kinematics_plugin-1] 
    [test_kinematics_plugin-1] [----------] Global test environment tear-down
    [test_kinematics_plugin-1] [==========] 8 tests from 1 test case ran. (2422 ms total)
    [test_kinematics_plugin-1] [  PASSED  ] 7 tests.
    [test_kinematics_plugin-1] [  FAILED  ] 1 test, listed below:
    [test_kinematics_plugin-1] [  FAILED  ] KinematicsTest.unitIK
    [test_kinematics_plugin-1] 
    [test_kinematics_plugin-1]  1 FAILED TEST
    [test_kinematics_plugin-1] [INFO] [1606313526.366020414] [test_kinematics_plugin]: getIKMultipleSolutions
    [test_kinematics_plugin-1] [INFO] [1606313526.366024392] [test_kinematics_plugin]: getIKMultipleSolutions
    [test_kinematics_plugin-1] [INFO] [1606313526.366031405] [test_kinematics_plugin]: Loading kdl_kinematics_plugin/KDLKinematicsPlugin
    [test_kinematics_plugin-1] Link base had 0 children
    [test_kinematics_plugin-1] Link link_1 had 1 children
    [test_kinematics_plugin-1] Link link_2 had 1 children
    [test_kinematics_plugin-1] Link link_3 had 1 children
    [test_kinematics_plugin-1] Link link_4 had 1 children
    [test_kinematics_plugin-1] Link link_5 had 1 children
    [test_kinematics_plugin-1] Link link_6 had 1 children
    [test_kinematics_plugin-1] Link tool0 had 0 children
    [test_kinematics_plugin-1] [INFO] [1606313526.366051533] [test_kinematics_plugin]: getNearestIKSolution
    [test_kinematics_plugin-1] [INFO] [1606313526.366055080] [test_kinematics_plugin]: getNearestIKSolution
    [ERROR] [test_kinematics_plugin-1]: process has died [pid 33690, exit code 1, cmd '/home/sebi/ws_ros2/install/moveit_kinematics/lib/moveit_kinematics/test_kinematics_plugin --ros-args -r __node:=fanuc_kdl_singular --params-file /tmp/launch_params_bvc4houn --params-file /tmp/launch_params_yl4ggea3 --params-file /tmp/launch_params_ifqa_pc3 --params-file /tmp/launch_params_sy2q8jmb --params-file /tmp/launch_params_5uhf1n_1 --params-file /tmp/launch_params_82mtfvie'].
    test_exit_codes (moveit_kinematics.TestOutcome) ... FAIL
    
    ======================================================================
    FAIL: test_exit_codes (moveit_kinematics.TestOutcome)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/sebi/ws_ros2/src/moveit2/moveit_kinematics/test/launch/fanuc-kdl-singular.test.py", line 132, in test_exit_codes
        launch_testing.asserts.assertExitCodes(proc_info)
      File "/opt/ros/foxy/lib/python3.8/site-packages/launch_testing/asserts/assert_exit_codes.py", line 62, in assertExitCodes
        assert info.returncode in allowable_exit_codes, 'Proc {} exited with code {}'.format(
    AssertionError: Proc test_kinematics_plugin-1 exited with code 1
    
    ----------------------------------------------------------------------
    Ran 1 test in 0.001s
    
    FAILED (failures=1)
    -- run_test.py: return code 1
    -- run_test.py: verify result file '/home/sebi/ws_ros2/build/moveit_kinematics/test_results/moveit_kinematics/test_launch_fanuc-kdl-singular.test.py.xunit.xml'
  >>>
build/moveit_kinematics/test_results/moveit_kinematics/test_launch_fanuc-kdl-singular.test.py.xunit.xml: 1 test, 0 errors, 1 failure, 0 skipped
- moveit_kinematics.TestOutcome test_exit_codes
  <<< failure message
    Traceback (most recent call last):
      File "/home/sebi/ws_ros2/src/moveit2/moveit_kinematics/test/launch/fanuc-kdl-singular.test.py", line 132, in test_exit_codes
        launch_testing.asserts.assertExitCodes(proc_info)
      File "/opt/ros/foxy/lib/python3.8/site-packages/launch_testing/asserts/assert_exit_codes.py", line 62, in assertExitCodes
        assert info.returncode in allowable_exit_codes, 'Proc {} exited with code {}'.format(
    AssertionError: Proc test_kinematics_plugin-1 exited with code 1
  >>>
build/moveit_kinematics/test_results/moveit_kinematics/test_launch_fanuc-kdl.test.py.xunit.xml: 1 test, 0 errors, 0 failures, 0 skipped
build/moveit_kinematics/test_results/moveit_kinematics/test_launch_panda-kdl-singular.test.py.xunit.xml: 1 test, 0 errors, 0 failures, 0 skipped
build/moveit_kinematics/test_results/moveit_kinematics/test_launch_panda-kdl.test.py.xunit.xml: 1 test, 0 errors, 0 failures, 0 skipped

Summary: 8 tests, 0 errors, 2 failures, 0 skipped
```

**Comment by sjahr** [comment]
Continued in #435

**Pull request closed without merging**
