### PR TITLE
[Foxy] Port MoveItConfigsBuilder 

### PR DESCRIPTION
**Pull request by DLu**
### Description

Part of #1449 

### Checklist
- [x] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] Extend the tutorials / documentation [reference](http://moveit.ros.org/documentation/contributing/)
- [x] Create tests, which fail without this PR [reference](https://ros-planning.github.io/moveit_tutorials/doc/tests/tests_tutorial.html)

### CODE REVIEW

**Comment by vatanaksoytezer** [comment]
@DLu Don't we need launches.py as well in moveit_configs_utils: https://github.com/ros-planning/moveit2/blob/main/moveit_configs_utils/moveit_configs_utils/launches.py

**Comment by DLu** [comment]
> @DLu Don't we need launches.py as well in moveit_configs_utils: https://github.com/ros-planning/moveit2/blob/main/moveit_configs_utils/moveit_configs_utils/launches.py

Eventually we will, but I was planning on doing that in future PRs as I adjust them for Foxy.

**Comment by DLu** [comment]
Tests are failing because `moveit_resources` is behind on the Foxy branch compared to `main`. (2.0.6 vs 2.0.3)

**Comment by vatanaksoytezer** [comment]
I think there were some breaking changes, which made us make a foxy branch. Do you think we can add necessary files to foxy branch of moveit_resource or arrange tests?

**Comment by sjahr** [comment]
Closing this since foxy EOL

**Pull request closed without merging**
