### PR TITLE
rename header files so debs are installable

### PR DESCRIPTION
**Pull request by mikeferguson**
### Description

These files were copied in, now causing installation issues for our Debians: https://github.com/ros-planning/moveit2/issues/1442

### Checklist
- [ ] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] Extend the tutorials / documentation [reference](http://moveit.ros.org/documentation/contributing/)
- [ ] Document API changes relevant to the user in the [MIGRATION.md](https://github.com/ros-planning/moveit/blob/master/MIGRATION.md) notes
- [ ] Create tests, which fail without this PR [reference](https://ros-planning.github.io/moveit_tutorials/doc/tests/tests_tutorial.html)
- [ ] Include a screenshot if changing a GUI
- [ ] While waiting for someone to review your request, please help review [another open pull request](https://github.com/ros-planning/moveit/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Comment by mikeferguson** [comment]
So it turns out this is more involved than I thought - the files we copied in are not what eventually got merged - in particular support for "namespace" has been lost - so our options are either:

 A) Remove the namespace usage within our codebase
 B) Keep the copied files, but rename them so we don't collide with the Debian
 C) Get an updated version into ros2_control, get that released, and then release this change

I'm not actually sure what option A even entails at this moment

**Review by tylerjw — APPROVED** [review]

**Comment by mikeferguson** [comment]
This now implements option B

**Comment by vatanaksoytezer** [comment]
@mikeferguson are we planning to eventually switch to option C, or keep it this way?

**Comment by mikeferguson** [comment]
@vatanaksoytezer I think we should eventually do option C (and I'll make sure there is a ticket for it) - but that is going to require at least 2 release cycles and somebody who is actually active on ros2_control (which I'm not). My goal with this PR is simply to get our debs to properly install - we can clean up the tech debt later

**Review by vatanaksoytezer — APPROVED** [review]

**Comment by vatanaksoytezer** [comment]
I'll try to cut a new release today.

**Comment by mikeferguson** [comment]
Ticketed Option C here: https://github.com/ros-planning/moveit2/issues/1451

**Pull request merged**
