### PR TITLE
Set project VERSION in moveit_common, fix sonames

### PR DESCRIPTION
**Pull request by henningkayser**
Fixes dependency issues in build farm due to invalid sonames (https://build.ros2.org/job/Gbin_uF64__moveit_ros_planning__ubuntu_focal_amd64__binary/2/console).

The issue is that `${PROJECT_NAME}_VERSION` is not set automatically with colcon, it needs to be set explicitly using `ament_package_xml()`. Since the sonames are configured in all packages by setting the VERSION property, the actual file name ends up ending with a `.`. With this fix the sonames are set to the corresponding package versions for all libraries. In the future we should consider setting up explicit ABI versions.

### CODE REVIEW

**Comment by jspricke** [comment]
Looks like this is not enough. Steps to reproduce:
```
cd moveit2/moveit_ros/occupancy_map_monitor
bloom-generate rosdebian --os-name ubuntu --os-version focal --ros-distro galactic
debuild
ls obj-x86_64-linux-gnu/libmoveit_ros_occupancy_map_monitor.so.
```
Though with colcon it builds a `libmoveit_ros_occupancy_map_monitor.so.2.2.0`

**Comment by davetcoleman** [comment]
Shouldn't this change be applied to all MoveIt2 packages?

**Comment by jspricke** [comment]
> Shouldn't this change be applied to all MoveIt2 packages?

No, Henning is changing the macro (and I missed that I had an old version installed, so retesting right now)

**Review by jspricke — APPROVED** [review]

**Comment by henningkayser** [comment]
> Shouldn't this change be applied to all MoveIt2 packages?

The `moveit_package` macro is actually applied to all MoveIt packages, so yes, but it's already done ;)

**Review by JafarAbdi — APPROVED** [review]

**Pull request merged**
