### PR TITLE
Feature/port orientation constraints

### PR DESCRIPTION
**Pull request by mipark56**
### Description

Please explain the changes you made, including a reference to the related issue if applicable

### Checklist
- [ ] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] Extend the tutorials / documentation [reference](http://moveit.ros.org/documentation/contributing/)
- [ ] Document API changes relevant to the user in the [MIGRATION.md](https://github.com/ros-planning/moveit/blob/master/MIGRATION.md) notes
- [ ] Create tests, which fail without this PR [reference](https://ros-planning.github.io/moveit_tutorials/doc/tests/tests_tutorial.html)
- [ ] Include a screenshot if changing a GUI
- [ ] While waiting for someone to review your request, please help review [another open pull request](https://github.com/ros-planning/moveit/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Comment by mipark56** [comment]
@vatanaksoytezer
Hi Vatan, tried to add you as a reviewer but couldn't seem to so tagging you here.  Feel free to add yourself.  If this PR was intended to be local within my fork (i.e. in this feature branch back to `https://github.com/mipark56/moveit2`), let me know and can close this and make one there.

Here's a quick summary of what I changed and build / test to see that the changes worked (I believe).

1. From this ticket https://github.com/ros-planning/moveit2/issues/348 , ported this PR, as outined / requested: https://github.com/ros-planning/moveit/pull/2402/files
2. From that diff, all orientation constraint parameterization changes, I simply copied over.
3. However, a few changes needed to be made, specific to ROS2, for example a.) Updated logging calls, e.g., `ROS_ERROR` to `RCLCPP_ERROR`, and b.) Updated messages namespace, e.g. `moveit_msg::OrientationConstraint` to `moveit_msgs::msg::OrientationConstraint`
4. After installing ROS 2 Foxy Fitzroy (side note: Galactic I could install but the rosdeps failed, preventing colcon build--if you're interested I can provide the name of the packages that halted the flow) from this guide: https://moveit.ros.org/install-moveit2/source/, I built the MoveIt2 suite with `colcon build --event-handlers desktop_notification- status- --cmake-args -DCMAKE_BUILD_TYPE=Release`
5. The colcon build seemed pretty computationally intensive--my gaming laptop fan was spinning full blast!
6. For the pre-formatting checks https://moveit.ros.org//documentation/contributing/code/ I found some trailing whitespace that I used VSCode settings to resolve.  Screenshot of the pre-commit checks below.
7. Lastly, I ran the demo setup https://github.com/ros-planning/moveit2/tree/main/moveit_demo_nodes/run_moveit_cpp to see the demo behavior in the RViz UI.  Screenshot on that below as well.

Thanks for reviewing this and if you've any follow up comments to things to look into, please comment here and I'll look into it.

image

image

image

**Comment by vatanaksoytezer** [comment]
Hey @mipark56 thanks for the PR! Great work! Sorry for the delayed review. Overall the port looks great, but to comment / clarify on a few points:

> If this PR was intended to be local within my fork (i.e. in this feature branch back to `https://github.com/mipark56/moveit2`), let me know and can close this and make one there.

This PR is intended for here. No worries on that.

> * From that diff, all orientation constraint parameterization changes, I simply copied over.

Can you squash this PR into 2 commits, so your changes and differences from the original PR will be more understandable:
1) Commit from the original PR (https://github.com/ros-planning/moveit/pull/2402)
2) ROS2 changes

> After installing ROS 2 Foxy Fitzroy (side note: Galactic I could install but the rosdeps failed, preventing colcon build--if you're interested I can provide the name of the packages that halted the flow) from this guide: https://moveit.ros.org/install-moveit2/source/, I built the MoveIt2 suite with `colcon build --event-handlers desktop_notification- status- --cmake-args -DCMAKE_BUILD_TYPE=Release`

Galactic should work right now, we were waiting for the latest Galactic sync that would enable MoveIt 2 to be built without additional repos (see #558 and https://github.com/ros-planning/moveit.ros.org/pull/617 for more context.) So that was missing documentation, on galactic compilation, but the extra repos are not needed now. Your code is builded against Rolling, Galactic and Foxy anyway by CI, so also no worries on this.

> The colcon build seemed pretty computationally intensive--my gaming laptop fan was spinning full blast!

It is, we recommend using ccache for consecutive builds to speed up the process (https://moveit.ros.org/install/source/). That is undocumented for ROS2 but should work the same way with ROS.

> * For the pre-formatting checks https://moveit.ros.org//documentation/contributing/code/ I found some trailing whitespace that I used VSCode settings to resolve. 

pre-commit will fix and format things for you, you should not need any extra steps or clean things manually. So should `pre-commit run -a` or `git commit -m "...."` after pre-commit hooks are installed should automatically fix your formatting.

I appreciate your work and it looks pretty clean. I would be happy if you can squash this into 2 commits as I've mentioned above, otherwise looks good to me!

**Comment by mipark56** [comment]
Hi @vatanaksoytezer, thanks for the review!  I updated the PR to combine the changes into the 2 commits you suggested.  I agree this makes the port cleaner while also pulling in the changes directly from the original PR links this change directly to that one within the git log (which is a good thing).  Let me know if you see anything else here that might need my attention.

**Review by vatanaksoytezer — APPROVED** [review]
Thanks for the commit cleanup, great work @mipark56. I think this can be merged after a maintainer approval.

**Comment by gautz** [comment]
@henningkayser The name of this PR is misleading. This is currently only the port of the new orientation parametrization which is already merged in MoveIt1. This is a prerequisite for adding Orientation constraints support to OMPL constrained planning. But there is currently no open PR on this. I could work on a PR in MoveIt1 that you could then port to MoveIt2. But for this I need this PR to be merged: https://github.com/ros-planning/moveit/pull/2273

@mipark56 @vatanaksoytezer do you plan to work on OMPL orientation constrained planning after this one is merged?

**Comment by vatanaksoytezer** [comment]
@gautz I don't think we have a clear plan to work on orientation constrain right now, I would appreciate if you can work on porting that and I would be happy to help getting it reviewed

**Review by henningkayser — APPROVED** [review]

**Pull request merged**
