### PR TITLE
add logos for dark and light themes

### PR DESCRIPTION
**Pull request by mamoll**
### Description

Add dark/light theme logos. CSS shows the right one in the API documentation. See https://github.com/ros-planning/moveit2_tutorials/pull/314 for related PR that also needs to merged for this to work.

### Checklist
- [ ] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] Extend the tutorials / documentation [reference](http://moveit.ros.org/documentation/contributing/)
- [ ] Document API changes relevant to the user in the [MIGRATION.md](https://github.com/ros-planning/moveit/blob/master/MIGRATION.md) notes
- [ ] Create tests, which fail without this PR [reference](https://ros-planning.github.io/moveit_tutorials/doc/tests/tests_tutorial.html)
- [ ] Include a screenshot if changing a GUI
- [ ] While waiting for someone to review your request, please help review [another open pull request](https://github.com/ros-planning/moveit/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Comment by mamoll** [comment]
> image
> 
> It looks like this in dark theme. Do we want two moveit2 logos or wait for figuring a way of switching in accordance with the theme?

It relies on the CSS in this PR: https://github.com/ros-planning/moveit2_tutorials/pull/314
Unfortunately, this means that when just looking at README.md in Github you see two logos. To me it's more important that the API web site looks right than the README.md.

**Comment by henningkayser** [comment]
@mamoll can't we set the [image context ](https://github.blog/changelog/2021-11-24-specify-theme-context-for-images-in-markdown/) like here? https://raw.githubusercontent.com/lutzroeder/netron/main/README.md

**Comment by mamoll** [comment]
> @mamoll can't we set the [image context ](https://github.blog/changelog/2021-11-24-specify-theme-context-for-images-in-markdown/) like here? https://raw.githubusercontent.com/lutzroeder/netron/main/README.md

Ooh! I didn't know you could do that. Neat. We need both the Github way and https://github.com/ros-planning/moveit2_tutorials/pull/314 to have things render correctly  on Github and the API web site, respectively.

**Comment by mamoll** [comment]
It doesn't work for me. See [logos-for-dark-and-light-themes branch](https://github.com/ros-planning/moveit2/tree/logos-for-dark-and-light-themes). I don't understand what I'm doing wrong.

**Comment by tylerjw** [comment]
@mamoll @henningkayser what should we do about this change? Should we merge it, close it, change it somehow?

**Comment by tylerjw** [comment]
I'm closing this for now, we can re-open it if we want to.

**Pull request closed without merging**
