### PR TITLE
Format includes using clang-format

### PR DESCRIPTION
**Pull request by tylerjw**
### Description

Replaces https://github.com/ros-planning/moveit2/pull/575

Uses clang-format to format includes and fixes missing includes.

I will backport the .clang-format change to moveit1 and fix any missing includes there too.

### CODE REVIEW

**Review by vatanaksoytezer — APPROVED** [review]
Looks neat!

**Review by henningkayser — APPROVED** [review]

**Comment by v4hn** [comment]
Please still reply to the comments from my last review https://github.com/ros-planning/moveit2/pull/575#pullrequestreview-718834437 .

Wouldn't it make sense to isolate `*_msgs` packages and `gtest`?

**Comment by tylerjw** [comment]
> Wouldn't it make sense to isolate `*_msgs` packages and `gtest`?

That seems easy enough.  I will make that change both here and in the moveit PR.

**Review by henningkayser — APPROVED** [review]

**Comment by tylerjw** [comment]
closing this for now... I'll bring it back if I care enough to fight over it.  There are much more important things to work on.

**Pull request closed without merging**
