### PR TITLE
Default to ninja, clang and lld

### PR DESCRIPTION
**Pull request by vatanaksoytezer**
Per @JafarAbdi s findings that this combination would result in fastest build times.

I'm not entirely sure about ninja not dumping the error messages though. We need to come up with something to upload the error.

### CODE REVIEW

**Comment by vatanaksoytezer** [comment]
Builds failing other than clang-tidy one seems to be because of caching

**Comment by vatanaksoytezer** [comment]
Seems clearing cache is on the way: https://github.com/github/roadmap/issues/502

**Comment by davetcoleman** [comment]
Hey vatan what's the status on this pr?

**Comment by tylerjw** [comment]
Closing. Creating an issue to track investigating CI times and potentially applying this change along with others.

**Comment by tylerjw** [comment]
https://github.com/ros-planning/moveit2/issues/1729

**Pull request closed without merging**
