### PR TITLE
Hybrid Planning

### PR DESCRIPTION
**Pull request by tylerjw**
### Description

Here is a PR for the hybrid planner.  I plan on doing the work to clean this up so it can be merged.

Here is the original hybrid planner PR: https://github.com/ros-planning/moveit2/pull/488

### Checklist
- [x] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] Extend the tutorials / documentation [reference](http://moveit.ros.org/documentation/contributing/)
- [ ] Document API changes relevant to the user in the [MIGRATION.md](https://github.com/ros-planning/moveit/blob/master/MIGRATION.md) notes
- [ ] Create tests, which fail without this PR [reference](https://ros-planning.github.io/moveit_tutorials/doc/tests/tests_tutorial.html)
- [ ] Include a screenshot if changing a GUI
- [ ] While waiting for someone to review your request, please help review [another open pull request](https://github.com/ros-planning/moveit/pulls) to support the maintainers

### CODE REVIEW

**Comment by tylerjw** [comment]
I am really confused as to how this would affect the servo tests in any way.  None of the servo PRs seem to be failing but this one is.

**Comment by sjahr** [comment]
@tylerjw Thanks for taking over! In the previous PR, I've marked the things I've addressed in #718 with ":thumbsup:". I don't know why the servo tests are failing, this is really weird.

**Comment by JensVanhooydonck** [comment]
I am having the following issues with this branch:
 - Multiple consecutive requests are not possible. In `single_plan_execution.cpp` the call_once of the local planner ensures that the local planner is only executed once. However, this is not reset when the local planner was successful. Replacing the `std::once_flag` with a Boolean and resetting after stopping the local planner seems to solve this. However I'm not sure this is thread safe.
 - When the global planner does not find a solution (Not possible or collision after smoothing) this crashes the Hybrid Planner Component container. In other words: if the initial path is not possible, it will not try again, or return that this path is not possible, but the hybrid container will stop.
 - It is not possible to pass a ompl_planning.yaml file to change the ompl planning parameters for the global planning.
 - The following parameters in the MotionPlanRequest are ignored:
    - max_velocity_scaling_factor
    - max_acceleration_scaling_factor
    - max_cartesian_speed
    - workspace_parameters.*
    - start_state.*

**Comment by AndyZe** [comment]
I find this branch  has broken the demo. One of the reasons, at least, is that the trajectory controller does not come up:

```
[component_container_mt-1] [WARN] [1637178427.024121523] [moveit.simple_controller_manager.gripper_controller_handle]: Waiting for panda_hand_controller/gripper_cmd to come up
[component_container_mt-1] [ERROR] [1637178427.024137421] [moveit.simple_controller_manager.gripper_controller_handle]: Action client not connected: panda_hand_controller/gripper_cmd
```

**Comment by frankchan12138** [comment]
> I am having the following issues with this branch:
> 
> * Multiple consecutive requests are not possible. In `single_plan_execution.cpp` the call_once of the local planner ensures that the local planner is only executed once. However, this is not reset when the local planner was successful. Replacing the `std::once_flag` with a Boolean and resetting after stopping the local planner seems to solve this. However I'm not sure this is thread safe.
> * When the global planner does not find a solution (Not possible or collision after smoothing) this crashes the Hybrid Planner Component container. In other words: if the initial path is not possible, it will not try again, or return that this path is not possible, but the hybrid container will stop.
> * It is not possible to pass a ompl_planning.yaml file to change the ompl planning parameters for the global planning.
> * The following parameters in the MotionPlanRequest are ignored:
>   
>   * max_velocity_scaling_factor
>   * max_acceleration_scaling_factor
>   * max_cartesian_speed
>   * workspace_parameters.*
>   * start_state.*

@JensVanhooydonck  Hello, right now I also try to use hybrid planning. Passing `ompl_planning.yaml` and modify `max_velocity_scaling_factor` do not work as you described. Have you figure out how to fix it? Any advice will be highly appreciated. Thanks!

**Comment by JensVanhooydonck** [comment]
> > I am having the following issues with this branch:
> > 
> > * Multiple consecutive requests are not possible. In `single_plan_execution.cpp` the call_once of the local planner ensures that the local planner is only executed once. However, this is not reset when the local planner was successful. Replacing the `std::once_flag` with a Boolean and resetting after stopping the local planner seems to solve this. However I'm not sure this is thread safe.
> > * When the global planner does not find a solution (Not possible or collision after smoothing) this crashes the Hybrid Planner Component container. In other words: if the initial path is not possible, it will not try again, or return that this path is not possible, but the hybrid container will stop.
> > * It is not possible to pass a ompl_planning.yaml file to change the ompl planning parameters for the global planning.
> > * The following parameters in the MotionPlanRequest are ignored:
> >   
> >   * max_velocity_scaling_factor
> >   * max_acceleration_scaling_factor
> >   * max_cartesian_speed
> >   * workspace_parameters.*
> >   * start_state.*
> 
> @JensVanhooydonck Hello, right now I also try to use hybrid planning. Passing `ompl_planning.yaml` and modify `max_velocity_scaling_factor` do not work as you described. Have you figure out how to fix it? Any advice will be highly appreciated. Thanks!

I didn't try this in the last year.. I don't know what the status is currently..

**Comment by frankchan12138** [comment]
@JensVanhooydonck  Thanks for reply! I will try to find a solution.

**Pull request closed without merging**
