### PR TITLE
Update pre-commit

### LINKED ISSUE #2093: Updating the pre-commit hooks in configuration files
### Description

The pre-commit hooks in the repository are old. Is there any reason for not updating them? Seems like, after the newest version, there have been quite a few changes to the repo by `codespell`.

### Your environment
* ROS Distro: Rolling
* OS Version: Ubuntu 22.04
* Source Build
* Branch: main
* RMW: Cyclone DDS

### Steps to reproduce
Run `pre-commit autoupdate` (as mentioned in the .yaml file) and then run the pre-commit with `pre-commit run -a`

### Expected behaviour
No change before and after updating pre-commit.

### Actual behaviour
Multiple file changes and suggestions by `codespell`.

### Backtrace or Console output

Use [gist.github.com](gist.github.com) to copy-paste the console output or segfault backtrace using gdb.

```
check for added large files..............................................Passed
check for case conflicts.................................................Passed
check json...........................................(no files to check)Skipped
check for merge conflicts................................................Passed
check for broken symlinks............................(no files to check)Skipped
check toml...........................................(no files to check)Skipped
check yaml...............................................................Passed
debug statements (python)................................................Passed
detect destroyed symlinks................................................Passed
detect private key.......................................................Passed
fix end of files.........................................................Passed
mixed line ending........................................................Passed
pretty format json...................................(no files to check)Skipped
trim trailing whitespace.................................................Passed
black....................................................................Passed
clang-format.............................................................Passed
codespell................................................................Failed
- hook id: codespell
- exit code: 65

moveit_ros/planning_interface/test/python_move_group_ns.py:38: possbile ==> possible, possibly
moveit_planners/ompl/ompl_interface/test/test_planning_context_manager.cpp:192: respone ==> response, respond
moveit_core/robot_state/src/attached_body.cpp:127: padd ==> pad, padded
moveit_core/robot_state/src/attached_body.cpp:133: padd ==> pad, padded
moveit_ros/planning_interface/test/subframes_test.cpp:17: SINIC ==> CYNIC, SONIC
moveit_planners/pilz_industrial_motion_planner/test/unit_tests/src/unittest_trajectory_generator_circ.cpp:653: constrainst ==> constraint, constraints
moveit_planners/pilz_industrial_motion_planner/test/unit_tests/src/unittest_trajectory_generator_circ.cpp:670: constrainst ==> constraint, constraints
```

### PR DESCRIPTION
**Pull request by Shobuj-Paul**
### Description

Updated pre-commit hooks and ran them in the repo.
Fixes #2093 

### Checklist
- [x] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] Extend the tutorials/documentation [reference](http://moveit.ros.org/documentation/contributing/)
- [ ] Document API changes relevant to the user in the [MIGRATION.md](https://github.com/ros-planning/moveit2/blob/main/MIGRATION.md) notes
- [ ] Create tests which fail without this PR [reference](https://moveit.picknik.ai/humble/doc/examples/tests/tests_tutorial.html)
- [ ] Include a screenshot if changing a GUI
- [ ] While waiting for someone to review your request, please help review [another open pull request](https://github.com/ros-planning/moveit2/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Comment by Shobuj-Paul** [comment]
Thanks, I have made the change.

**Review by JafarAbdi — APPROVED** [review]

**Comment by Shobuj-Paul** [comment]
Tried updating clang-format-14 to clang-format-15, but there is some major conflict which I could not understand so reverted the commits

**Comment by Shobuj-Paul** [comment]
Can someone please help me with this? Updating `clang-format-15` causes issues with rolling-ci+ikfast workflow. Logs show that it is failing to clone. How are the two things related?
Or am I missing something else entirely?

**Comment by JafarAbdi** [comment]
@Shobuj-Paul Please revert the change to the clang-format version, we use a system installed one and changing it might cause issues with other people

**Comment by Shobuj-Paul** [comment]
@JafarAbdi 
Even after rolling it back to the previous commit, the same test fails. I am not sure why it worked before but is not working now.

**Comment by vatanaksoytezer** [comment]
@Shobuj-Paul I think ikfast failure is not related to your changes:

```
Error downloading object: benchmarking/databases/panda_kitchen_test_db.sqlite (b6b06bb): Smudge error: Error downloading benchmarking/databases/panda_kitchen_test_db.sqlite (b6b06bbbbe0eb6fe0dacc6d44386051b4d48e884b77a256697912ecdd09f528c): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
```

**Comment by Shobuj-Paul** [comment]
> @Shobuj-Paul I think ikfast failure is not related to your changes:
> 
> ```
> Error downloading object: benchmarking/databases/panda_kitchen_test_db.sqlite (b6b06bb): Smudge error: Error downloading benchmarking/databases/panda_kitchen_test_db.sqlite (b6b06bbbbe0eb6fe0dacc6d44386051b4d48e884b77a256697912ecdd09f528c): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
> ```

I thought as much, thanks for confirming.

**Review by JafarAbdi — COMMENTED** [review]
Thanks for the follow-ups! just one issue and I'll merge

The changes to the .eps files will break them, right? I think we should ignore them in the spell-checker hook

**Comment by Shobuj-Paul** [comment]
> Thanks for the follow-ups! just one issue and I'll merge
> 
> The changes to the .eps files will break them, right? I think we should ignore them in the spell-checker hook

My bad, I didn't think even the .eps files will be edited. I have excluded all .eps files in the pre-commit configuration and reverted the changes from before.

**Pull request merged**
