### PR TITLE
Clean OpenSSL dependencies

### PR DESCRIPTION
**Pull request by vatanaksoytezer**
prerelease on Rolling was failing in my fork with current master with SSL errors: https://github.com/vatanaksoytezer/moveit2/runs/2909420963?check_suite_focus=true

I just applied the same solution with https://github.com/ros-planning/warehouse_ros_mongo/pull/63. Now I can confirm that pre-release is passing on Rolling https://github.com/vatanaksoytezer/moveit2/runs/2909699212?check_suite_focus=true.

Galactic prerelease still fails because of geometric shapes failing on Galactic in buildfarm due to a bloom issue I suppose (see https://build.ros2.org/job/Gsrc_uF__geometric_shapes__ubuntu_focal__source/12/console)

### CODE REVIEW

**Review by JafarAbdi — CHANGES_REQUESTED** [review]
I don't see where `libssl-dev` is being used in `moveit_ros_warehouse`, I think the solution should be to remove OpenSSl from [CMakeLists.txt](https://github.com/ros-planning/moveit2/blob/main/moveit_ros/warehouse/CMakeLists.txt#L19), [${OPENSSL_INCLUDE_DIR}](https://github.com/ros-planning/moveit2/blob/main/moveit_ros/warehouse/CMakeLists.txt#L24), and [target_link_libraries](https://github.com/ros-planning/moveit2/blob/main/moveit_ros/warehouse/warehouse/CMakeLists.txt#L14)

**Review by JafarAbdi — APPROVED** [review]

**Comment by vatanaksoytezer** [comment]
This will fail until https://github.com/ros-planning/warehouse_ros/pull/80 is merged. prerelease failure turned out to be a warehouse_ros export issue. We will now need to get a new Rolling and Galactic release for `warehouse_ros` to pass prerelease tests.

**Comment by tylerjw** [comment]
I merged the PR in warehouse_ros and re-triggered all the CI jobs for this PR.

**Comment by vatanaksoytezer** [comment]
> I merged the PR in warehouse_ros and re-triggered all the CI jobs for this PR.

Thanks! Foxy and Rolling CIs doesn't seem re-triggered for me though 🤔. Can you check that @tylerjw ?

**Review by henningkayser — APPROVED** [review]

**Review by henningkayser — APPROVED** [review]

**Pull request merged**
