### PR TITLE
Delete packages which are not being built

### PR DESCRIPTION
**Pull request by ChrisThrasher**
### Description

I deleted all packages containing `COLCON_IGNORE` since by the fact that they're not being built, they're not being used. We can resurrect this code later if we change our mind.

### CODE REVIEW

**Review by tylerjw — APPROVED** [review]

**Review by sjahr — APPROVED** [review]
Good idea :+1: The code in these packages is probably 3 years outdated by now because I am not sure if the unported moveit1 packages got synchronized. If :man_shrugging:  any of these packages will be ported to moveit2 in the future, the first step should be to copy the latest version of the package from moveit1 anyways.

**Review by henningkayser — CHANGES_REQUESTED** [review]
Did you investigate what you are removing? Originally, these packages have been ignored due to migration in order to preserve the commit history, which is really useful for understanding the context for a lot of the code. I'm ok with removing `moveit_commander` and `moveit_experimental` since the first one is being made obsolete by the new python bindings (#1546 removes these parts as well), and I can't recall `moveit_experimental` ever being of much use. Trajopt should definitely not be removed, it's way too recent and it's still being worked on (https://github.com/ros-planning/moveit/pull/3235), and we should rather find a way to complete migration. I'm unsure about the MSA parts, @DLu (author) might have some thoughts if it's worth migrating or if it should be reimplemented from scratch. In general, I think it's very important in OSS to preserve authorship and commit history. Ignored packages are very little dead weight and trivial to sync with changes from ROS 1.

Edit: I just noticed that there is even an open issue to complete the MSA simulation work https://github.com/ros-planning/moveit2/issues/1262, so I would suggest not removing the code but rather try to find some time to make it work.

**Comment by ChrisThrasher** [comment]
> I think it's very important in OSS to preserve authorship and commit history.

What is not being preserved? Anyone can still look through the commit history to see who added this now-unused code.

**Comment by ChrisThrasher** [comment]
I put trajopts and moveit_setup_assistant back so now this PR only removes moveit_experimental and moveit_commander.

**Comment by henningkayser** [comment]
> What is not being preserved? Anyone can still look through the commit history to see who added this now-unused code. That's the whole point of version control.

The last version will not list the commits with git blame, and the person that copied back the code or reverted the removal commit will be the new author. https://moveit.ros.org/documentation/contributing/maintainer_pr/#the-latest-branch-preserves-all-original-commits

**Review by henningkayser — APPROVED** [review]

**Comment by PeterMitrano** [comment]
Very happy to see `moveit_commander` being deleted... makes more spaces for #1546 to be the one and only option!!! :tada:

**Pull request merged**
