### PR TITLE
Test using debians test from industrial_ci

### PR DESCRIPTION
**Pull request by tylerjw**
### Description

This is a test of using this from industrial_ci instead of the pre-release feature that doesn't seem to work: https://github.com/ros-industrial/industrial_ci/pull/719

### CODE REVIEW

**Comment by tylerjw** [comment]
Linking this because it should fix the python3 issue: https://github.com/ros-infrastructure/bloom/pull/661

**Comment by jspricke** [comment]
a fixed bloom was released, finally. Can you retrigger this to test?

**Comment by tylerjw** [comment]
Rebased and trying again.

**Comment by jspricke** [comment]
humble fails with:
```
2022-11-18T03:00:34.6466478Z /usr/bin/ld: /opt/ros/humble/lib/librsl.a(random.cpp.o): relocation R_X86_64_TPOFF32 against `_ZZN3rsl3rngESt8seed_seqE5first' can not be used when making a shared object; recompile with -fPIC
```
I guess we need to wait for a new rsl...

**Comment by tylerjw** [comment]
This has conflicts and we stopped working on this almost a year ago. I'm closing it for now.

**Pull request closed without merging**
