### PR TITLE
Removed moveit_jog_arm for renaming and relocating

### PR DESCRIPTION
**Pull request by AdamPettinger**
### Description

This PR only removes `moveit_jog_arm` from the `moveit_experimental` folder. The intent is to add it back soon with a different name (likely `moveit_servo`) in a new location (likely `moveit_ros`), and do all jogger related ROS2 transitioning and improvement work there with direction from @AndyZe and @tylerjw 

I would think this PR will stay open until jog_arm is added back in, and I will link to that when it happens. Just wanted to give some time for naming and location feedback first :smiley: 

### Checklist
- [ ] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] Extend the tutorials / documentation [reference](http://moveit.ros.org/documentation/contributing/)
- [ ] Document API changes relevant to the user in the MIGRATION.md notes
- [ ] Create tests, which fail without this PR [reference](https://ros-planning.github.io/moveit_tutorials/)
- [ ] Include a screenshot if changing a GUI
- [ ] While waiting for someone to review your request, please help review [another open pull request](https://github.com/ros-planning/moveit/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Comment by henningkayser** [comment]
@AdamPettinger Thanks for starting this! I think that we should sync the latest (pending) progress from MoveIt 1 once the PR's are merged and make sure to keep the history when renaming/moving this package. In general, are you planning to work in a feature branch and file PRs for milestones or would you rather keep on adding frequent changes to master?

**Comment by AdamPettinger** [comment]
> I think that we should sync the latest (pending) progress from MoveIt 1 once the PR's are merged and make sure to keep the history when renaming/moving this package.

Sounds like a good plan, although I don't know the actual mechanisms of doing that. In that case, this PR will probably be rebased after that pending progress is merged, and expanded to include the renaming and relocation as well.

> In general, are you planning to work in a feature branch and file PRs for milestones or would you rather keep on adding frequent changes to master?

I have not decided yet, but if one is definitively easier for maintainers/reviewers, let's do that one.

**Comment by AdamPettinger** [comment]
@henningkayser I think I will be ready to start with the ROS2 side soon.

I discussed with @AndyZe and @tylerjw, and they thought the best approach might be to just copy the most recent version of `jog_arm` from the ROS1 work and push it here, and not worry too much about the git history. Is that something you're comfortable with? If not, how do we get the changes to here with git history?

**Comment by henningkayser** [comment]
> @henningkayser I think I will be ready to start with the ROS2 side soon.
> 
> I discussed with @AndyZe and @tylerjw, and they thought the best approach might be to just copy the most recent version of `jog_arm` from the ROS1 work and push it here, and not worry too much about the git history. Is that something you're comfortable with? If not, how do we get the changes to here with git history?

@AdamPettinger I would prefer to use a filtered merge for this and keep the history consistent.
Can you do this after https://github.com/ros-planning/moveit/pull/2151 is merged?

**Comment by AdamPettinger** [comment]
@henningkayser I think I did it with #221, please verify that. If it looks good, I will rebase this PR on top of that and add commits to move the files instead of just deleting them

**Comment by henningkayser** [comment]
continued in #221 #222

**Pull request closed without merging**
