### PR TITLE
Add buildfarm badges

### LINKED ISSUE #531: Add buildfarm badges for Foxy, Galactic and Rolling

### PR DESCRIPTION
**Pull request by vatanaksoytezer**
Adds ROS 2 Buildfarm badges and closes #531.

### CODE REVIEW

**Review by tylerjw — APPROVED** [review]
lgtm

**Review by auman66 — APPROVED** [review]
Buildfarm table in the readme looks very nice. Its crazy that everything is green. I didn't check every link, but I trust @vatanaksoytezer to have included the correct ones

**Comment by tylerjw** [comment]
Will merge after this is approved/merged (which will fix foxy): https://github.com/ros-planning/moveit2/pull/565

**Review by henningkayser — APPROVED** [review]
Such a huge list! But it's great to see this all in one spot. I find it a little clunky for the top of the README, should we move this further down or into a separate page?

**Comment by vatanaksoytezer** [comment]
> Such a huge list! But it's great to see this all in one spot. I find it a little clunky for the top of the README, should we move this further down or into a separate page?

I think it is good to be have badges visible somewhere in README. I am totally fine to move it a little bit down.

**Comment by tylerjw** [comment]
I agree with Henning, do you mind just placing this table at the bottom of the README?

**Pull request merged**
