### PR TITLE
Melodic-devel sync

### PR DESCRIPTION
**Pull request by henningkayser**
There are some more commits to sync this time.
@davetcoleman I followed your instructions from [here](https://github.com/ros-planning/moveit2/pull/26) and used a merge commit for syncing my master-branch. There were some simple conflicts so that Github added two merge commits. Should I squash those?

Alternatively we could use `rebase --onto` so we don't have extra merge commits but potentially altered history.

### CODE REVIEW

**Comment by mlautman** [comment]
I reviewed the changes and they don't seem to modify any of the ROS2 progress so +1 there.

`rebase --onto` seems better to me but @rhaschke pushed for merge commits. Personally, I prefer cherry-picking or rebasing over merging whenever possible as merge-commits dirty up the git history quite a bit. So long as the cherry-picking is going from MoveIt1 -> MoveIt2 I don't see why that would change the commit history..

**Comment by davetcoleman** [comment]
We have [GitHub Merge Policies](https://moveit.ros.org/documentation/contributing/pullrequests/) and I don't claim to be an expert but basically @v4hn says merging is fine sometimes.

> potentially altered history.

Will this break the synchronization with acutronic/moveit2?

**Comment by rhaschke** [comment]
Definitely, please use merge commits! Using cherry-picks, it becomes terribly hard to really keep track of all changes. With merge commits, you can immediately recognize which commits are missing.

> There were some simple conflicts so that Github added two merge commits.

@henningkayser, I don't get why you have two merge commits here (in both directions). Did you use github to resolve conflicts? I can try later to do a cleaner merge.

**Comment by rhaschke** [comment]
Closing in favor of #36.

**Comment by henningkayser** [comment]
> Definitely, please use merge commits! Using cherry-picks, it becomes terribly hard to really keep track of all changes. With merge commits, you can immediately recognize which commits are missing.
> 
> > There were some simple conflicts so that Github added two merge commits.
> 
> @henningkayser, I don't get why you have two merge commits here (in both directions). Did you use github to resolve conflicts? I can try later to do a cleaner merge.

Yes I used Github to resolve conflicts which added the first commit and then merged the PR which added the second one.
I'm really not a friend of Github's web interface since it sometimes does strange things.
@rhaschke Thanks for cleaning this up

**Pull request closed without merging**
