### PR TITLE
Add missing dependency to servo

### PR DESCRIPTION
**Pull request by tylerjw**
### Description

This is part of the answer to https://github.com/ros-planning/moveit2/issues/597

I still don't know where `panda_arm_controller` and the teleop demo doesn't seem to work (frame is wrong in rviz and it prints a ton of errors about collisions).  I am testing on rolling.

### CODE REVIEW

**Review by vatanaksoytezer — APPROVED** [review]
I've also had this error in my servo test PR in #603, I can confirm that this fixes the CI and my local runs.

**Comment by AdamPettinger** [comment]
I believe the Panda controller is from [here](https://github.com/ros-planning/moveit_resources/blob/ros2/panda_moveit_config/config/panda_controllers.yaml), and loaded into the Servo demos like [this](https://github.com/ros-planning/moveit2_tutorials/blob/84af78cff8f63cc9d67e39df1df2e995310c068d/doc/realtime_servo/launch/servo_teleop.launch.py#L70-L75)

> teleop demo doesn't seem to work (frame is wrong in rviz and it prints a ton of errors about collisions)

I am trying to replicate. Just want to verify you mean the [servo_teleop](https://github.com/ros-/planning/moveit2_tutorials/blob/main/doc/realtime_servo/launch/servo_teleop.launch.py) demo over in `moveit2_tutorials`, yes?

**Review by AdamPettinger — APPROVED** [review]
I found an issue with the TF static publisher frame names and fixed it in https://github.com/ros-planning/moveit2_tutorials/pull/104. Will you take a look and try it out? Otherwise this dependency addition worked

**Review by henningkayser — COMMENTED** [review]
The packages inside `moveit_demo_nodes` and `moveit_ros_planning_interface` are missing this one as well. Could you add it to them?

**Comment by tylerjw** [comment]
closing as another change fixed this

**Comment by vatanaksoytezer** [comment]
> The packages inside `moveit_demo_nodes` and `moveit_ros_planning_interface` are missing this one as well. Could you add it to them?

@tylerjw isn't this still valid?

**Pull request closed without merging**
