### PR TITLE
WIP: HPP FCL Plugin

### PR DESCRIPTION
**Pull request by vatanaksoytezer**
Adresses #1435 by creating a new hpp-fcl plugin for MoveIt. Binaries of hpp-fcl are due to be available on tomorrow's sync so I would wait for that at least.

### CODE REVIEW

**Comment by simonschmeisser** [comment]
Very interesting, just a short general comment: When copying and modifying files it's nice to do this in separate commits so it's easier to see in github what changes were necessary besides renaming

**Comment by vatanaksoytezer** [comment]
> Very interesting, just a short general comment: When copying and modifying files it's nice to do this in separate commits so it's easier to see in github what changes were necessary besides renaming

Thank you for the suggestion, I'll revise the commit history as soon as this is ready for reviews. I need to get some non-moveit work this week but I'm hoping I can get things going next week.

**Comment by simonschmeisser** [comment]
For MoveIt 1 HPP FCL is not extremely impressive unfortunately
grafik

**Comment by tylerjw** [comment]
It looks like this PR is no longer being worked on as it was determined it did not offer the hoped for performance benefits.

**Comment by simonschmeisser** [comment]
Just for completeness: hpp fcl does offer a newer api for collision checks and this might speed up things in fact. Also hpp fcl might be faster at the narrow phase, especially mesh to mesh, which my benchmarks do not test that well. I still hope to finish the MoveIt 1 PR and then this could be ported

**Pull request closed without merging**
