### PR TITLE
[MSA] SRDF Setup

### PR DESCRIPTION
**Pull request by DLu**
### Description

 * Ports the remaining SRDF configuration steps (PlanningGroups/RobotPoses/EndEffectors/PassiveJoints) to the new framework
 * Makes some changes to the existing SRDF configuration steps (DefaultCollisions/VirtualJoints) to take advantage of shared code. 

#### Squashed Bug
**Edit:** I fixed this with https://github.com/ros-planning/moveit2/pull/1057/commits/5f77106cf5307d38fa51e6f3a8b980dac89ae1a3

~~As mentioned in `MIGRATION.md` there is currently a bug that I can't figure out. Steps to reproduce:~~
 * ~~Start MSA with new configuration~~
 * ~~Configure a PlanningGroup~~
 *  ~~Try to make a pose for your new Group. It should give you an error because it can't find the associated `JointModelGroup`~~

### Checklist
- [x] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] Extend the tutorials / documentation [reference](http://moveit.ros.org/documentation/contributing/)
- [ ] Document API changes relevant to the user in the [MIGRATION.md](https://github.com/ros-planning/moveit/blob/master/MIGRATION.md) notes
- [ ] Create tests, which fail without this PR [reference](https://ros-planning.github.io/moveit_tutorials/doc/tests/tests_tutorial.html)
- [ ] Include a screenshot if changing a GUI
- [ ] While waiting for someone to review your request, please help review [another open pull request](https://github.com/ros-planning/moveit/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Comment by vatanaksoytezer** [comment]
@DLu thanks a ton for the PR. I'll review this tomorrow and get back to you. In the meantime do we want to merge immediately with the bug you mentioned or hold until it's resolved. It seemed critical enough to me.

**Comment by DLu** [comment]
Nah, let's review and investigate the bug here

**Comment by vatanaksoytezer** [comment]
clang-tidy has a few complaints @DLu

**Comment by DLu** [comment]
Fixed the major bug. Ready for review.

**Review by vatanaksoytezer — APPROVED** [review]
I just tested this and looks good

**Pull request merged**
