### PR TITLE
[moveit_cpp] Fix config of multiple pipelines

### PR DESCRIPTION
**Pull request by galou**
Signed-off-by: Gaël Écorchard <gael.ecorchard@cvut.cz>

### Description

The issue I had was that MoveItCpp was working with one pipeline but when I wanted to configure a second pipeline, I couldn't use the first one.

### Checklist
- [x] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] Extend the tutorials / documentation [reference](http://moveit.ros.org/documentation/contributing/)
- [ ] Document API changes relevant to the user in the [MIGRATION.md](https://github.com/ros-planning/moveit/blob/master/MIGRATION.md) notes
- [ ] Create tests, which fail without this PR [reference](https://ros-planning.github.io/moveit_tutorials/doc/tests/tests_tutorial.html)
- [ ] Include a screenshot if changing a GUI
- [ ] While waiting for someone to review your request, please help review [another open pull request](https://github.com/ros-planning/moveit/pulls) to support the maintainers

Do I really need to write a test for such a change?

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

Edit: Added PR description

### CODE REVIEW

**Review by v4hn — APPROVED** [review]
> Testing this change would require launching a node with the configuration of two pipelines. Then I don't know how I could check the internal state of the node (group_pipelines_map_).

Well, apparently you hit a bug or you would not have created this patch called "Fix". You can definitely check for whether the buggy behavior is fixed. :)
Looking at this further the whole code is a mess. The only place where this map is used in `getPlanningPipelineNames` and there it's even used as a lookup to *verify* whether the planner exists for this group instead of just taking the set of pipelines from there... It's clearly not faster that way, as the comment here claims...

I would much prefer a proper cleanup of these methods instead of this one-line patch, but the patch itself is correct.

**Comment by galou** [comment]
@v4hn I can't agree more with you. The issue I had was that MoveItCpp was working with one pipeline but when I wanted to configure a second pipeline, I couldn't use the first one. I took me two days to figure out that the reason was not my configuration but the code itself.

**Comment by v4hn** [comment]
> The issue I had was that MoveItCpp was working with one pipeline but when I wanted to configure a second pipeline, I couldn't use the first one. I took me two days to figure out that the reason was not my configuration but the code itself.

It might have been a good idea to have these sentences in the PR description already ;)

**Review by henningkayser — APPROVED** [review]

**Comment by v4hn** [comment]
> henningkayser approved this pull request.

Please merge if you want. I rather approved above, but I still think someone who wrote these methods (you? ;)) should rewrite them instead.

**Pull request merged**
