### PR TITLE
MoveIt Servo should respect the AllowedCollisionMatrix

### PR DESCRIPTION
**Pull request by amalnanavati**
### Description

As it currently stands, MoveIt Servo uses the AllowedCollisionMatrix (ACM) when checking for self-collisions, but not for checking environment-collisions. This is a problem, as we may want to temporarily allow collisions with certain objects in the planning scene during servo-ing (e.g., if the planning scene is slightly inaccurate, or if we want the robot to make contact with a surface while servo-ing).

This one-line change addresses that, by making the environment-collision checking call also take in the ACM.

### Testing

I tested this on our local robot setup in ROS2 Humble, by servoing the robot to an object in the planning scene, verifying that it decelerated/halted, then changing the ACM to allow collisions between that part of the planning scene and the rest of the robot links, and verifying that I could then servo through it without decelerating/halting.

### Requested Backport

I'd love a Humble backport of this, although I know that may be hard to automate due to the large structural changes Servo's code has gone through since the Humble release. Happy to create a separate PR for Humble if necessary.

### Checklist
- [x] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [N/A] Extend the tutorials / documentation [reference](http://moveit.ros.org/documentation/contributing/)
- [N/A] Document API changes relevant to the user in the [MIGRATION.md](https://github.com/ros-planning/moveit2/blob/main/MIGRATION.md) notes
- [ ] Create tests, which fail without this PR [reference](https://moveit.picknik.ai/humble/doc/examples/tests/tests_tutorial.html)
- [N/A] Include a screenshot if changing a GUI
- [ ] While waiting for someone to review your request, please help review [another open pull request](https://github.com/ros-planning/moveit2/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Comment by sjahr** [comment]
@amalnanavati Do you mind running [pre-commit](https://moveit.ros.org/documentation/contributing/code/#pre-commit-formatting-checks) to fix formatting

**Comment by amalnanavati** [comment]
The `humble-ci-testing` failure seems to be the same one documented [here](https://github.com/ros-planning/moveit2/pull/2601#issuecomment-1855500808), where the `ros2_control_node` is segfaulting ([relevant line in logs](https://github.com/ros-planning/moveit2/actions/runs/7212871760/job/19651497395#step:12:9344)). I believe that is unrelated to this PR.

**Review by sea-bass — APPROVED** [review]
Thanks for these contributions!

**Comment by amalnanavati** [comment]
Are we waiting for another approving review? Or can this be merged?

**Comment by sea-bass** [comment]
> Are we waiting for another approving review? Or can this be merged?

Yeah, we need at least one maintainer approval, but most people are out on holidays (myself included). It will be merged soon!

**Review by sjahr — APPROVED** [review]

**Comment by amalnanavati** [comment]
Thanks! Could you add a humble back port tag to this please?

**Comment by sea-bass** [comment]
> Thanks! Could you add a humble back port tag to this please?

Humble again had significant code changes in servo, but I could chase it down in this case -- see https://github.com/ros-planning/moveit2/pull/2643

**Pull request merged**
