### PR TITLE
[MSA] Testing Framework for MoveItSetupAssistant

### PR DESCRIPTION
**Pull request by DLu**
### Description

Adds a nice testing harness for easy checking of generated files. 

New Features:
 * Updated sensor configuration format
 * Keep trajectory execution parameters around

Tests
 * Ported the ROS 1 tests for perception and controllers
 * Added some SRDF Planning Groups tests

### Checklist
- [x] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] Extend the tutorials / documentation [reference](http://moveit.ros.org/documentation/contributing/)
- [ ] Document API changes relevant to the user in the [MIGRATION.md](https://github.com/ros-planning/moveit/blob/master/MIGRATION.md) notes
- [x] Create tests, which fail without this PR [reference](https://ros-planning.github.io/moveit_tutorials/doc/tests/tests_tutorial.html)
- [ ] Include a screenshot if changing a GUI
- [ ] While waiting for someone to review your request, please help review [another open pull request](https://github.com/ros-planning/moveit/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Comment by vatanaksoytezer** [comment]
@DLu do you mind changing the target branch to main, now that we have the feature branch merged?

**Comment by mikeferguson** [comment]
As a note - this adds some tests that will be wrong once we fix the format of the sensors_3d.yaml load/export in https://github.com/ros-planning/moveit2/pull/1398

**Comment by mikeferguson** [comment]
Looking at this PR, I'm also noticing a few other things about sensors_3d.yaml:

 * the templates/sensor_3d.yaml isn't actually used by the MSA at this point (so that description at the top of the file is somewhat misleading). It would actually be nice to load the default values for the text boxes from this file.
 * format of the templates/sensor_3d.yaml file is wrong - sensors should be a list of names, and then each of the sensor configurations should be namespaces under their name (lists of heterogenous items like this can't really be loaded as ROS2 params AFAIK).

**Comment by DLu** [comment]
Updated description above, ready for review

**Review by mikeferguson — APPROVED** [review]
Looks good to me - not sure what's going on with the test coverage showing as down 10% ?? Anybody know what's up with that?

**Review by vatanaksoytezer — APPROVED** [review]

**Comment by vatanaksoytezer** [comment]
> not sure what's going on with the test coverage showing as down 10% ?? Anybody know what's up with that?

Maybe because of some caching we were getting an inaccurate test coverage before, and this PR fixed the cache by having a lot of changes? That's my best bet.

**Comment by DLu** [comment]
I've long wondered about the efficacy of the bot, and now I'm sure something's not right.

**Pull request merged**
