### PR TITLE
Enable Servo Tests

### LINKED ISSUE #397: Flaky tests in moveit_servo
### Description

When migrating to GitHub Actions I discovered that two of the moveit_servo tests are flaky.  In that PR I disabled them by commenting out them from the CMakeLists.txt.  This issue is to track fixing those tests.  I'm marking this good-first-issue because it is an isolated task.  However, teasing out why they are flaky might not be trivial.

The tests are:
* unit_test_servo_calcs
* test_servo_pose_tracking

### PR DESCRIPTION
**Pull request by vatanaksoytezer**
With the recent fixes on Rolling and Galactic's `ComposobleNodeContainer`, we should be able to enable these tests safely. Closes #397.

### CODE REVIEW

**Comment by vatanaksoytezer** [comment]
@tylerjw @JafarAbdi can you rerun the CI (around 10~ish times) before you merge this? I tried 22 times in my fork without any problems before, but you know ... just in case :)

**Comment by vatanaksoytezer** [comment]
Test seem to fail because of #597

**Review by AndyZe — APPROVED** [review]
Looks good. My only comment is that you also deleted some tests that have been commented for quite some time. Please add that to the commit description. Maybe squash your commits and use a description like this:

`Enable Servo tests. Delete the servo_cpp_interface tests that have not been ported yet`

**Comment by vatanaksoytezer** [comment]
> `Enable Servo tests. Delete the servo_cpp_interface tests that have not been ported yet`

Those are ported actually, in basic_servo_tests.cpp that's why I deleted them. Nevertheless, I will squash and update the commit message 👍🏻

**Review by tylerjw — APPROVED** [review]
Sweet, thank you.  I ran it locally a dozen times and it passed each time.

**Review by henningkayser — APPROVED** [review]

**Pull request merged**
