### PR TITLE
Enforce -Wpedantic

### PR DESCRIPTION
**Pull request by henningkayser**

### CODE REVIEW

**Comment by henningkayser** [comment]
wondering about the upcoming errors in CI, it took me a while to notice that I wasn't compiling all packages locally...

**Comment by henningkayser** [comment]
I just switched to gcc10 and still doesn't find the extra-semicolon warnings. Are we running a very old gcc version by any chance? I recall we once had to add extra semicolons just to remove them later on. Currently, it's not consistent, though. My guess is that we would have to enforce certain compiler versions in CI if we really want to go with this.

**Comment by v4hn** [comment]
Wasn't https://github.com/ros-planning/moveit/commit/ef085558818e7e4fbc97e41f8dd12a1a2d6dbfa0 ported?

**Comment by tylerjw** [comment]
Following the instructions for running industrial_ci locally I am able to run the clang test like this:

```
ros2 run industrial_ci rerun_ci $PWD/src/moveit2 \
  CXXFLAGS='-Wall -Wextra -Wwrite-strings -Wunreachable-code -Wpointer-arith -Wredundant-decls -Wno-deprecated-copy -Wpedantic' \
  DOCKER_IMAGE='ghcr.io/ros-planning/moveit2:rolling-ci' \
  UPSTREAM_WORKSPACE='moveit2.repos' \
  TARGET_CMAKE_ARGS='-DCMAKE_BUILD_TYPE=Release' \
  CCACHE_DIR="$HOME/.ccache" \
  CLANG_TIDY_BASE_REF='main' \
  BEFORE_CLANG_TIDY_CHECKS='(cd $TARGET_REPO_PATH; clang-tidy --list-checks)' \
  CC='clang' CXX='clang++' \
  CLANG_TIDY='pedantic'
```

This fails with a bunch of clang-tidy errors.

**Comment by tylerjw** [comment]
Created issue to track finishing this work here: https://github.com/ros-planning/moveit2/issues/1730

**Pull request closed without merging**
